package view;

import dao.HoaDonChiTietDAO;
import dao.HoaDonDAO;
import dao.SanPhamDAO;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.HoaDonChiTiet;
import model.SanPham;

/**
 *
 * @author Hoang
 */
public class Panel_DonHang extends javax.swing.JPanel {

    /**
     * Creates new form panel_san_pham
     */
    public Panel_DonHang() {
        initComponents();
    }

    public void setdata() {
        modelHoaDonChiTiet.addColumn("STT");
        modelHoaDonChiTiet.addColumn("Mã SP");
        modelHoaDonChiTiet.addColumn("Tên SP");
        modelHoaDonChiTiet.addColumn("Tồn Kho");
        modelHoaDonChiTiet.addColumn("Số Lượng Mua");
        modelHoaDonChiTiet.addColumn("Giá Bán");
        modelHoaDonChiTiet.addColumn("Thành Tiền");

        tbl_DonHang.setModel(modelHoaDonChiTiet);
        tbl_DonHang.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbl_DonHang.getColumnModel().getColumn(2).setPreferredWidth(300);
        tbl_DonHang.getColumnModel().getColumn(3).setPreferredWidth(50);
        tbl_DonHang.getColumnModel().getColumn(4).setPreferredWidth(50);
        tbl_DonHang.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbl_DonHang.getColumnModel().getColumn(6).setPreferredWidth(150);

        tbl_DonHang.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexHoaDonChiTiet = tbl_DonHang.getSelectedRow();
        });

        txt_TongTien.setEditable(false);
        txt_TongTien.setText("0 đ");
        rdo_nam.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_gioiTInh = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DonHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_xoaDonHang = new javax.swing.JButton();
        btn_themDonHang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        txt_soluong = new javax.swing.JTextField();
        btn_timSanPham = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_timKhachHang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        txt_tenKhachHang = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JLabel();
        btn_xoaTatCa = new javax.swing.JButton();
        btn_luuHoaDon = new javax.swing.JButton();
        txt_maSanPham = new javax.swing.JLabel();
        txt_tenSanPham = new javax.swing.JLabel();
        txt_loaiSanPham = new javax.swing.JLabel();
        txt_hangSanXuat = new javax.swing.JLabel();

        tbl_DonHang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tbl_DonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Tồn Kho", "Số Lượng Mua", "Giá Bán", "Thành Tiền"
            }
        ));
        tbl_DonHang.setRowHeight(20);
        tbl_DonHang.getTableHeader().setFont(new Font("Dialog", 0, 14));
        jScrollPane1.setViewportView(tbl_DonHang);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Mã Sản Phẩm:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tên Sản Phẩm:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Số Lượng Mua:");

        btn_xoaDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/xoa.png"))); // NOI18N
        btn_xoaDonHang.setText("Xóa Khỏi Đơn Hàng");
        btn_xoaDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaDonHangActionPerformed(evt);
            }
        });

        btn_themDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_themDonHang.setText("Thêm Vào Đơn Hàng");
        btn_themDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themDonHangActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Tổng TIền");

        txt_TongTien.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txt_TongTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        txt_soluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_soluongKeyPressed(evt);
            }
        });

        btn_timSanPham.setText("Tìm SP");
        btn_timSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timSanPhamActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Loại Sản Phẩm:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Hãng Sản Xuất:");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tên Khách Hàng:");

        btn_timKhachHang.setText("Tìm KH");
        btn_timKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKhachHangActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Số ĐT:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Giới Tính:");

        grp_gioiTInh.add(rdo_nam);
        rdo_nam.setText("Nam");
        rdo_nam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdo_namFocusGained(evt);
            }
        });
        rdo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_namActionPerformed(evt);
            }
        });

        grp_gioiTInh.add(rdo_nu);
        rdo_nu.setText("Nữ");
        rdo_nu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdo_nuFocusGained(evt);
            }
        });
        rdo_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_nuActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Ghi Chú:");

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChu);

        txt_tenKhachHang.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_tenKhachHang.setForeground(java.awt.Color.blue);
        txt_tenKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_soDienThoai.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_soDienThoai.setForeground(java.awt.Color.blue);
        txt_soDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btn_timKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_nam)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_nu))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_nam)
                    .addComponent(rdo_nu))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btn_xoaTatCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/broom2.png"))); // NOI18N
        btn_xoaTatCa.setText("Xóa Tất Cả");
        btn_xoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTatCaActionPerformed(evt);
            }
        });

        btn_luuHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luuHoaDon.setText("Lưu Hóa Đơn");
        btn_luuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuHoaDonActionPerformed(evt);
            }
        });

        txt_maSanPham.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_maSanPham.setForeground(java.awt.Color.blue);
        txt_maSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_tenSanPham.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_tenSanPham.setForeground(java.awt.Color.blue);
        txt_tenSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_loaiSanPham.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_loaiSanPham.setForeground(java.awt.Color.blue);
        txt_loaiSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_hangSanXuat.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_hangSanXuat.setForeground(java.awt.Color.blue);
        txt_hangSanXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_loaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_hangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_luuHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_xoaTatCa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_xoaDonHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_timSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_themDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_maSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_timSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_themDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_xoaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_loaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_xoaTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_hangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_luuHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Mã Sản PHẩm:");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timSanPhamActionPerformed
        // TODO add your handling code here:
        new Popup_TimKiemSanPham(-1).setVisible(true);
    }//GEN-LAST:event_btn_timSanPhamActionPerformed

    private void btn_themDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themDonHangActionPerformed
        // TODO add your handling code here:
        themDonHang();
    }//GEN-LAST:event_btn_themDonHangActionPerformed

    private void themDonHang() {
        if (checkValidateDonHang()) {
            try {
                addListHoaDonChiTiet();
                loadModelHoaDonChiTiet();

                txt_maSanPham.setText("");
                txt_tenSanPham.setText("");
                txt_loaiSanPham.setText("");
                txt_hangSanXuat.setText("");
                txt_soluong.setText("");

                tbl_DonHang.setRowSelectionInterval(modelHoaDonChiTiet.getRowCount() - 1, modelHoaDonChiTiet.getRowCount() - 1);

            } catch (IllegalArgumentException iae) {
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi thêm đơn hàng");
                System.out.println(e);
            }
        }
    }

    private void addListHoaDonChiTiet() {
        boolean isDuplicate = false;
        for (HoaDonChiTiet hoaDonChiTiet : listHoaDonChiTiet) {
            if (hoaDonChiTiet.getSanPham().getMaSanPham() == maSanPham) {
                isDuplicate = true;
                hoaDonChiTiet.setSoLuong(hoaDonChiTiet.getSoLuong() + soLuong);
                break;
            }
        }
        if (!isDuplicate) {
            HoaDonChiTiet hoaDonChiTiet = new HoaDonChiTiet();
            hoaDonChiTiet.setSanPham(sanPham);
            hoaDonChiTiet.setSoLuong(soLuong);
            listHoaDonChiTiet.add(hoaDonChiTiet);
        }
    }

    private void btn_xoaDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaDonHangActionPerformed
        // TODO add your handling code here:
        temp_indexHoaDonChiTiet = indexHoaDonChiTiet;

        maSanPham = txt_maSanPham.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maSanPham.getText()) : -1;
        if (indexHoaDonChiTiet >= 0) {
            try {
                listHoaDonChiTiet.remove(indexHoaDonChiTiet);
                loadModelHoaDonChiTiet();

                if (temp_indexHoaDonChiTiet == 0) {
                    tbl_DonHang.setRowSelectionInterval(0, 0);
                } else {
                    tbl_DonHang.setRowSelectionInterval(temp_indexHoaDonChiTiet - 1, temp_indexHoaDonChiTiet - 1);
                }

            } catch (IllegalArgumentException iea) {
            } catch (Exception e4) {
                System.out.println(e4);
            }
        }
    }//GEN-LAST:event_btn_xoaDonHangActionPerformed

    private void btn_timKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKhachHangActionPerformed
        // TODO add your handling code here:
        new Popup_TimKiemKhachHang().setVisible(true);
    }//GEN-LAST:event_btn_timKhachHangActionPerformed

    private void txt_soluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soluongKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            themDonHang();
        }
    }//GEN-LAST:event_txt_soluongKeyPressed

    private void btn_xoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTatCaActionPerformed
        // TODO add your handling code here:
        xoaTatCa();
    }//GEN-LAST:event_btn_xoaTatCaActionPerformed

    public void xoaTatCa() {
        try {
            listHoaDonChiTiet.clear();
            loadModelHoaDonChiTiet();

            maKhachHang = -1;
            txt_tenKhachHang.setText("");
            txt_soDienThoai.setText("");
            rdo_nam.setSelected(true);
            txt_ghiChu.setText("");
            txt_maSanPham.setText("");
            txt_tenSanPham.setText("");
            txt_loaiSanPham.setText("");
            txt_hangSanXuat.setText("");
            txt_soluong.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void btn_luuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuHoaDonActionPerformed
        // TODO add your handling code here:
        if (checkValidateHoaDon()) {
            hoaDonDAO.them(taiKhoan, maKhachHang, tongTien, ngayLapHoaDon, ghiChu, listHoaDonChiTiet);
            JOptionPane.showMessageDialog(this, "Lưu hóa đơn thành công");
            xoaTatCa();
        }
    }//GEN-LAST:event_btn_luuHoaDonActionPerformed

    private void rdo_namFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdo_namFocusGained
        // TODO add your handling code here:
        temp_rdo_nam = rdo_nam.isSelected();
    }//GEN-LAST:event_rdo_namFocusGained

    private void rdo_nuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdo_nuFocusGained
        // TODO add your handling code here:
        temp_rdo_nam = !rdo_nu.isSelected();
    }//GEN-LAST:event_rdo_nuFocusGained

    private void rdo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_namActionPerformed
        // TODO add your handling code here:
        if (!temp_rdo_nam) {
            rdo_nu.setSelected(true);
        }
    }//GEN-LAST:event_rdo_namActionPerformed

    private void rdo_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_nuActionPerformed
        // TODO add your handling code here:
        if (temp_rdo_nam) {
            rdo_nam.setSelected(true);
        }
    }//GEN-LAST:event_rdo_nuActionPerformed

    private boolean checkValidateDonHang() {
        maSanPham = txt_maSanPham.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maSanPham.getText()) : -1;
        soLuong = txt_soluong.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_soluong.getText()) : -1;

        if (maSanPham == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn SP");
            return false;
        }
        if (soLuong < 1) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ");
            txt_soluong.requestFocus();
            return false;
        }

        sanPham = sanPhamDAO.getSanPhamById(maSanPham);
        int soluong_ = soLuong;
        for (HoaDonChiTiet hoaDonChiTiet : listHoaDonChiTiet) {
            if (hoaDonChiTiet.getSanPham().getMaSanPham() == maSanPham) {
                soluong_ += hoaDonChiTiet.getSoLuong();
                break;
            }
        }
        if (soluong_ > sanPham.getTonKho()) {
            JOptionPane.showMessageDialog(this, "Vượt quá số lượng tồn kho của Sản phẩm");
            return false;
        }

        return true;
    }

    private boolean checkValidateHoaDon() {
        taiKhoan = TrangChu.taiKhoan;
        if (maKhachHang == -1 || txt_tenKhachHang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa chọn Khách Hàng");
            return false;
        }
        if (listHoaDonChiTiet.isEmpty() || modelHoaDonChiTiet.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn SP");
            return false;
        }

        ngayLapHoaDon = format.format(new java.util.Date());
        ghiChu = txt_ghiChu.getText();
        return true;
    }

    private void loadModelHoaDonChiTiet() {
        int stt = 1;
        tongTien = 0;
        modelHoaDonChiTiet.setRowCount(0);
        for (HoaDonChiTiet hoaDonChiTiet : listHoaDonChiTiet) {
            Vector row = new Vector();
            row.add(stt++);
            row.add(hoaDonChiTiet.getSanPham().getMaSanPham());
            row.add(hoaDonChiTiet.getSanPham().getTenSanPham());
            row.add(hoaDonChiTiet.getSanPham().getTonKho());
            row.add(hoaDonChiTiet.getSoLuong());
            row.add(format(hoaDonChiTiet.getSanPham().getGiaBan()));
            int thanhTien = hoaDonChiTiet.getSanPham().getGiaBan() * hoaDonChiTiet.getSoLuong();
            row.add(format(thanhTien));
            modelHoaDonChiTiet.addRow(row);
            tongTien += thanhTien;
        }
        txt_TongTien.setText(format(tongTien));
    }

    SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    DefaultTableModel modelHoaDonChiTiet = new DefaultTableModel();

    List<HoaDonChiTiet> listHoaDonChiTiet = new ArrayList<>();

    HoaDonDAO hoaDonDAO = new HoaDonDAO();
    HoaDonChiTietDAO hoaDonChiTietDAO = new HoaDonChiTietDAO();
    SanPhamDAO sanPhamDAO = new SanPhamDAO();

    int indexHoaDonChiTiet = -1;
    int temp_indexHoaDonChiTiet = -1;

    private String taiKhoan;
    private int maSanPham;
    private int soLuong;
    private long tongTien = 0;
    static int maKhachHang = -1;
    private SanPham sanPham;
    private String ngayLapHoaDon;
    private String ghiChu;
    boolean temp_rdo_nam;

    public static String format(int gia) {
        return new DecimalFormat("#,###").format(gia).replace(",", ".") + " đ";
    }

    public static String format(long gia) {
        return new DecimalFormat("#,###").format(gia).replace(",", ".") + " đ";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luuHoaDon;
    private javax.swing.JButton btn_themDonHang;
    private javax.swing.JButton btn_timKhachHang;
    private javax.swing.JButton btn_timSanPham;
    private javax.swing.JButton btn_xoaDonHang;
    private javax.swing.JButton btn_xoaTatCa;
    protected static javax.swing.ButtonGroup grp_gioiTInh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    protected static javax.swing.JRadioButton rdo_nam;
    protected static javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tbl_DonHang;
    private javax.swing.JTextField txt_TongTien;
    private javax.swing.JTextArea txt_ghiChu;
    protected static javax.swing.JLabel txt_hangSanXuat;
    protected static javax.swing.JLabel txt_loaiSanPham;
    protected static javax.swing.JLabel txt_maSanPham;
    protected static javax.swing.JLabel txt_soDienThoai;
    protected static javax.swing.JTextField txt_soluong;
    protected static javax.swing.JLabel txt_tenKhachHang;
    protected static javax.swing.JLabel txt_tenSanPham;
    // End of variables declaration//GEN-END:variables
}
