package view;

import dao.HangSanXuatDAO;
import dao.LoaiSanPhamDAO;
import dao.SanPhamDAO;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.HangSanXuat;
import model.LoaiSanPham;
import model.SanPham;

/**
 *
 * @author Hoang
 */
public class Panel_SanPham extends javax.swing.JPanel {

    /**
     * Creates new form panel_san_pham
     */
    public Panel_SanPham() {
        initComponents();
    }

    public void setdata(){
        modelSanPham.addColumn("ID");
        modelSanPham.addColumn("Tên");
        modelSanPham.addColumn("Loại");
        modelSanPham.addColumn("Hãng");
        modelSanPham.addColumn("Giá Nhập");
        modelSanPham.addColumn("Giá Bán");
        modelSanPham.addColumn("Tồn Kho");
        modelSanPham.addColumn("Ghi Chú");
        
        cbo_loaiSanPham.setModel(modelLoaiSanPham);
        cbo_hangSanXuat.setModel(modelHangSanXuat);
        tbl_SanPham.setModel(modelSanPham);
        
        tbl_SanPham.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexSanPham = tbl_SanPham.getSelectedRow();
            if(indexSanPham>=0 && !isEditable){
                txt_maSanPham.setText(tbl_SanPham.getValueAt(indexSanPham, 0).toString());
                txt_tenSanPham.setText(tbl_SanPham.getValueAt(indexSanPham, 1).toString());
                cbo_loaiSanPham.setModel(new DefaultComboBoxModel<>(new String[]{tbl_SanPham.getValueAt(indexSanPham, 2).toString()}));
                cbo_hangSanXuat.setModel(new DefaultComboBoxModel<>(new String[]{tbl_SanPham.getValueAt(indexSanPham, 3).toString()}));
                txt_giaNhap.setText(tbl_SanPham.getValueAt(indexSanPham, 4).toString());
                txt_giaBan.setText(tbl_SanPham.getValueAt(indexSanPham, 5).toString());
                txt_ghiChu.setText(tbl_SanPham.getValueAt(indexSanPham, 7)==null?"":tbl_SanPham.getValueAt(indexSanPham, 7).toString());
                
            } else if (isUpdate){
                
            } else if (isEditable){
                
            }
        });
        
        loadSanPham();
        
        setEditable(false);
        txt_maSanPham.setEditable(false);
        try {
            if(modelSanPham.getRowCount()>0) tbl_SanPham.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }
    
    public void loadSanPham(){
        setEditable(false);
        isUpdate = false;
        listSanPham.clear();
        modelSanPham.setRowCount(0);
        
        listSanPham = sanPhamDAO.getList();
        listSanPham.forEach(sanPham -> {
            Vector row = new Vector();
            row.add(sanPham.getMaSanPham());
            row.add(sanPham.getTenSanPham());
            row.add(sanPham.getLoaiSanPham().getTenLoaiSanPham());
            row.add(sanPham.getHangSanXuat().getTenHangSanXuat());
            row.add(Panel_DonHang.format(sanPham.getGiaNhap()));
            row.add(Panel_DonHang.format(sanPham.getGiaBan()));
            row.add(sanPham.getTonKho());
            row.add(sanPham.getGhiChu());
            modelSanPham.addRow(row);
        });
        
        listLoaiSanPham.clear();
        modelLoaiSanPham.removeAllElements();
        modelLoaiSanPham.addElement("-- Chọn Loại SP--");
        listLoaiSanPham = loaiSanPhamDAO.getListLoaiSanPham();
        listLoaiSanPham.forEach((loaiSanPham) -> {
            modelLoaiSanPham.addElement(loaiSanPham.getTenLoaiSanPham());
        });
        
        listHangSanXuat.clear();
        modelHangSanXuat.removeAllElements();
        modelHangSanXuat.addElement("-- Chọn HSX--");
        listHangSanXuat = hangSanXuatDAO.getListHangSanXuat();
        listHangSanXuat.forEach((hangSanXuat) -> {
            modelHangSanXuat.addElement(hangSanXuat.getTenHangSanXuat());
        });
        
        if(modelSanPham.getRowCount()>0){
            try {
                tbl_SanPham.setRowSelectionInterval(0, 0);
            } catch (Exception e) {}
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SanPham = new javax.swing.JTable();
        txt_tenSanPham = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbo_loaiSanPham = new javax.swing.JComboBox<>();
        btn_boqua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbo_hangSanXuat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_giaNhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_giaBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        txt_maSanPham = new javax.swing.JTextField();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        btn_lamMoiDanhSach = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        tbl_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Loại", "Hãng", "Giá Nhập", "Giá Bán", "Tồn Kho", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tbl_SanPham);

        jLabel1.setText("Mã Sản Phẩm");

        jLabel2.setText("Tên Sản Phẩm");

        cbo_loaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_boqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/boqua.png"))); // NOI18N
        btn_boqua.setText("Bỏ Qua");
        btn_boqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boquaActionPerformed(evt);
            }
        });

        jLabel3.setText("Loại Sản Phẩm");

        cbo_hangSanXuat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Hãng Sản Xuất");

        jLabel5.setText("Giá Nhập");

        jLabel6.setText("Giá Bán");

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChu);

        jLabel8.setText("Ghi Chú");

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_them.setText("Tạo Mới");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/sua.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/xoa.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_timkiem.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/timkiem.png"))); // NOI18N
        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_lamMoiDanhSach.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btn_lamMoiDanhSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/refresh.png"))); // NOI18N
        btn_lamMoiDanhSach.setText("Làm Mới Danh Sách");
        btn_lamMoiDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiDanhSachActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 13)); // NOI18N
        jLabel7.setText("* Tìm kiếm sản phẩm theo mã, tên hoặc loại, hãng SX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_timkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_lamMoiDanhSach))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_lamMoiDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbo_loaiSanPham, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_tenSanPham, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maSanPham, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_hangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txt_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_boqua, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 358, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_maSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbo_loaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbo_hangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_boqua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        temp_indexSanPham = indexSanPham;
        setEditable(true);
        txt_tenSanPham.requestFocus();
        txt_maSanPham.setText("");
        txt_tenSanPham.setText("");
        txt_giaNhap.setText("");
        txt_giaBan.setText("");
        txt_ghiChu.setText("");
        cbo_hangSanXuat.setSelectedIndex(0);
        cbo_loaiSanPham.setSelectedIndex(0);
        tbl_SanPham.clearSelection();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        temp_indexSanPham = indexSanPham;
        String loaiSanPham = cbo_loaiSanPham.getSelectedItem().toString();
        String hangSanXuat = cbo_hangSanXuat.getSelectedItem().toString();
        setEditable(true);
        isUpdate = true;
        txt_tenSanPham.requestFocus();
        cbo_loaiSanPham.setSelectedItem(loaiSanPham);
        cbo_hangSanXuat.setSelectedItem(hangSanXuat);
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        temp_indexSanPham = indexSanPham;
        JLabel confirm = new JLabel("Xác nhận xóa sản phẩm "+txt_tenSanPham.getText()+"?");
        confirm.setFont(new Font("Dialog", Font.PLAIN, 17));
        int a = JOptionPane.showConfirmDialog(this, confirm, "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == JOptionPane.YES_OPTION) {
            maSanPham = txt_maSanPham.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maSanPham.getText()) : -1;
            if (indexSanPham >= 0) {
                try {
                    sanPhamDAO.xoa(maSanPham);
                    loadSanPham();
                    if(temp_indexSanPham == 0) tbl_SanPham.setRowSelectionInterval(0, 0);
                    else tbl_SanPham.setRowSelectionInterval(temp_indexSanPham-1, temp_indexSanPham-1);
                    
                } catch(IllegalArgumentException iea){
                } catch (Exception e4){
                    System.out.println(e4);
                }
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (checkValidate()) {
            if (!isUpdate) {
                try {
                    sanPhamDAO.them(tenSanPham, maLoaiSanPham, maHangSanXuat, giaNhap, giaBan, imagePath, ghiChu);
                    loadSanPham();
                    tbl_SanPham.setRowSelectionInterval(modelSanPham.getRowCount()-1, modelSanPham.getRowCount()-1);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi thêm sản phẩm");
                    System.out.println(e);
                }
            } else {
                try {
                    sanPhamDAO.sua(maSanPham ,tenSanPham, maLoaiSanPham, maHangSanXuat, giaNhap, giaBan, imagePath, ghiChu);
                    loadSanPham();
                    tbl_SanPham.clearSelection();
                    tbl_SanPham.setRowSelectionInterval(temp_indexSanPham, temp_indexSanPham);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi sửa sản phẩm");
                    System.out.println(e);
                }
                
            }
            
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_boquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boquaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
        isUpdate = false;
        try {
            tbl_SanPham.clearSelection();
            tbl_SanPham.setRowSelectionInterval(temp_indexSanPham, temp_indexSanPham);
        } catch (Exception e) {}
    }//GEN-LAST:event_btn_boquaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String text = txt_timKiem.getText().trim();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập dữ liệu tìm kiếm");
            
        } else {
            listSanPham.clear();
            modelSanPham.setRowCount(0);
            listSanPham = sanPhamDAO.timKiem(text);
            listSanPham.forEach(sanPham -> {
                Vector row = new Vector();
                row.add(sanPham.getMaSanPham());
                row.add(sanPham.getTenSanPham());
                row.add(sanPham.getLoaiSanPham().getTenLoaiSanPham());
                row.add(sanPham.getHangSanXuat().getTenHangSanXuat());
                row.add(Panel_DonHang.format(sanPham.getGiaNhap()));
                row.add(Panel_DonHang.format(sanPham.getGiaBan()));
                row.add(sanPham.getTonKho());
                row.add(sanPham.getGhiChu());
                modelSanPham.addRow(row);
            });
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_lamMoiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiDanhSachActionPerformed
        // TODO add your handling code here:
        loadSanPham();
    }//GEN-LAST:event_btn_lamMoiDanhSachActionPerformed

    public boolean checkValidate() {
        maSanPham = txt_maSanPham.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maSanPham.getText()) : -1;
        tenSanPham = txt_tenSanPham.getText().trim();
        if(cbo_loaiSanPham.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Chưa chọn Loại sản phẩm");
            cbo_loaiSanPham.requestFocus();
            return false;
        }
        if(cbo_hangSanXuat.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Chưa chọn Hãng sản xuất");
            cbo_hangSanXuat.requestFocus();
            return false;
        }
        maLoaiSanPham = listLoaiSanPham.stream().filter(loaiSanPham -> (cbo_loaiSanPham.getSelectedItem().toString().equals(loaiSanPham.getTenLoaiSanPham()))).findAny().orElse(null).getMaLoaiSanPham();
        maHangSanXuat = listHangSanXuat.stream().filter(hangSanXuat -> (cbo_hangSanXuat.getSelectedItem().toString().equals(hangSanXuat.getTenHangSanXuat()))).findAny().orElse(null).getMaHangSanXuat();
        giaNhap = txt_giaNhap.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_giaNhap.getText()) : -1;
        giaBan = txt_giaBan.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_giaBan.getText()) : -1;
        ghiChu = txt_ghiChu.getText().trim();
        
        if(tenSanPham.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Tên sản phẩm");
            txt_tenSanPham.requestFocus();
            return false;
        }
        if(giaNhap == -1){
            JOptionPane.showMessageDialog(this, "Giá nhập phải nhập số");
            txt_giaNhap.requestFocus();
            return false;
        }
        if(giaBan == -1){
            JOptionPane.showMessageDialog(this, "Giá bán phải nhập số");
            txt_giaBan.requestFocus();
            return false;
        }
        if(ghiChu.length()>100){
            JOptionPane.showMessageDialog(this, "Ghi chú phải nhỏ hơn 100 kí tự");
            txt_ghiChu.requestFocus();
            return false;
        }
        imagePath = "";
        return true;
    }
    
    public void setEditable(boolean isEditable) {
            this.isEditable = isEditable;

            btn_them.setEnabled(!isEditable);
            btn_sua.setEnabled(!isEditable);
            btn_xoa.setEnabled(!isEditable);
            btn_luu.setEnabled(isEditable);
            btn_boqua.setEnabled(isEditable);
            btn_timkiem.setEnabled(!isEditable);

            txt_tenSanPham.setEditable(isEditable);
            txt_giaNhap.setEditable(isEditable);
            txt_giaBan.setEditable(isEditable);
            txt_ghiChu.setEditable(isEditable);

            if (isEditable) {
                cbo_hangSanXuat.setModel(modelHangSanXuat);
                cbo_loaiSanPham.setModel(modelLoaiSanPham);
                
                txt_giaNhap.setText(txt_giaNhap.getText().replaceAll("[^\\d]", ""));
                txt_giaBan.setText(txt_giaBan.getText().replaceAll("[^\\d]", ""));
            } else {
                
            }
    }
    
    DefaultTableModel modelSanPham = new DefaultTableModel();
    DefaultComboBoxModel<String> modelLoaiSanPham = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> modelHangSanXuat = new DefaultComboBoxModel<>();
    
    List<SanPham> listSanPham = new ArrayList<>();
    List<LoaiSanPham> listLoaiSanPham = new ArrayList<>();
    List<HangSanXuat> listHangSanXuat = new ArrayList<>();
    
    SanPhamDAO sanPhamDAO = new SanPhamDAO();
    LoaiSanPhamDAO loaiSanPhamDAO = new LoaiSanPhamDAO();
    HangSanXuatDAO hangSanXuatDAO = new HangSanXuatDAO();
    
    int indexSanPham = -1;
    int temp_indexSanPham = -1;
    
    boolean isEditable = false;
    boolean isUpdate = false;
    
    private int maSanPham;
    private String tenSanPham;
    private int maLoaiSanPham;
    private int maHangSanXuat;
    private int giaNhap;
    private int giaBan;
    private String imagePath;
    private String ghiChu;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_boqua;
    private javax.swing.JButton btn_lamMoiDanhSach;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_hangSanXuat;
    private javax.swing.JComboBox<String> cbo_loaiSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_SanPham;
    private javax.swing.JTextArea txt_ghiChu;
    private javax.swing.JTextField txt_giaBan;
    private javax.swing.JTextField txt_giaNhap;
    private javax.swing.JTextField txt_maSanPham;
    private javax.swing.JTextField txt_tenSanPham;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
