package view;

import dao.KhachHangDAO;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;

/**
 *
 * @author Hoang
 */
public class Panel_KhachHang extends javax.swing.JPanel {

    /**
     * Creates new form panel_san_pham
     */
    public Panel_KhachHang() {
        initComponents();
    }

    public void setdata(){
        modelKhachHang.addColumn("Mã Khách Hàng");
        modelKhachHang.addColumn("Họ Tên");
        modelKhachHang.addColumn("Giới Tính");
        modelKhachHang.addColumn("Số ĐT");
        modelKhachHang.addColumn("Ghi Chú");
        
        tbl_KhachHang.setModel(modelKhachHang);
        
        tbl_KhachHang.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexKhachHang = tbl_KhachHang.getSelectedRow();
            if(indexKhachHang>=0 && !isEditable){
                txt_maKhachHang.setText(tbl_KhachHang.getValueAt(indexKhachHang, 0).toString());
                txt_tenKhachHang.setText(tbl_KhachHang.getValueAt(indexKhachHang, 1).toString());
                if(tbl_KhachHang.getValueAt(indexKhachHang, 2).toString().equals("Nam")) rdo_nam.setSelected(true);
                else rdo_nu.setSelected(true);
                txt_soDienThoai.setText(tbl_KhachHang.getValueAt(indexKhachHang, 3).toString());
                txt_ghiChu.setText(tbl_KhachHang.getValueAt(indexKhachHang, 4)==null?"":tbl_KhachHang.getValueAt(indexKhachHang, 4).toString());
                
            } else if (isUpdate){
                
            } else if (isEditable){
                
            }
        });
        
        loadKhachHang();
        
        setEditable(false);
        txt_maKhachHang.setEditable(false);
        try {
            if(modelKhachHang.getRowCount()>0) tbl_KhachHang.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }
    
    public void loadKhachHang(){
        setEditable(false);
        isUpdate = false;
        listKhachHang.clear();
        modelKhachHang.setRowCount(0);
        
        listKhachHang = khachHangDAO.getList();
        listKhachHang.forEach(khachHang -> {
            Vector row = new Vector();
            row.add(khachHang.getMaKhachHang());
            row.add(khachHang.getTenKhachHang());
            row.add(khachHang.isGioiTinh()==true?"Nam":"Nữ");
            row.add(khachHang.getSoDienThoai());
            row.add(khachHang.getGhiChu());
            modelKhachHang.addRow(row);
        });
        
        if(modelKhachHang.getRowCount()>0){
            try {
                tbl_KhachHang.setRowSelectionInterval(0, 0);
            } catch (Exception e) {}
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_gioiTinh = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KhachHang = new javax.swing.JTable();
        txt_tenKhachHang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_boqua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        txt_maKhachHang = new javax.swing.JTextField();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        btn_lamMoiDanhSach = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        txt_soDienThoai = new javax.swing.JTextField();

        tbl_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Họ Tên", "Giới Tính", "Số ĐT", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tbl_KhachHang);

        jLabel1.setText("Mã Khách Hàng");

        jLabel2.setText("Họ Tên");

        btn_boqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/boqua.png"))); // NOI18N
        btn_boqua.setText("Bỏ Qua");
        btn_boqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boquaActionPerformed(evt);
            }
        });

        jLabel3.setText("Giới Tính");

        jLabel4.setText("Số ĐT");

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChu);

        jLabel8.setText("Ghi Chú");

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_them.setText("Tạo Mới");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/sua.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/xoa.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_timkiem.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/timkiem.png"))); // NOI18N
        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_lamMoiDanhSach.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btn_lamMoiDanhSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/refresh.png"))); // NOI18N
        btn_lamMoiDanhSach.setText("Làm Mới Danh Sách");
        btn_lamMoiDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiDanhSachActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 13)); // NOI18N
        jLabel7.setText("* Tìm kiếm khách hàng theo tên hoặc số ĐT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_timkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_lamMoiDanhSach))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lamMoiDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grp_gioiTinh.add(rdo_nam);
        rdo_nam.setText("Nam");
        rdo_nam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdo_namFocusGained(evt);
            }
        });
        rdo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_namActionPerformed(evt);
            }
        });

        grp_gioiTinh.add(rdo_nu);
        rdo_nu.setText("Nữ");
        rdo_nu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdo_nuFocusGained(evt);
            }
        });
        rdo_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_nuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(472, 472, 472))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_tenKhachHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                        .addComponent(txt_maKhachHang, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdo_nam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdo_nu)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_boqua, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 358, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_maKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdo_nam)
                                    .addComponent(rdo_nu)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btn_boqua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        temp_indexKhachHang = indexKhachHang;
        setEditable(true);
        txt_maKhachHang.setText("");
        txt_tenKhachHang.requestFocus();
        txt_tenKhachHang.setText("");
        rdo_nam.setSelected(true);
        txt_soDienThoai.setText("");
        txt_ghiChu.setText("");
        tbl_KhachHang.clearSelection();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        temp_indexKhachHang = indexKhachHang;
        setEditable(true);
        isUpdate = true;
        txt_tenKhachHang.requestFocus();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        temp_indexKhachHang = indexKhachHang;
        JLabel confirm = new JLabel("Xác nhận xóa khách hàng "+txt_tenKhachHang.getText()+"?");
        confirm.setFont(new Font("Dialog", Font.PLAIN, 17));
        int a = JOptionPane.showConfirmDialog(this, confirm, "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == JOptionPane.YES_OPTION) {
            maKhachHang = txt_maKhachHang.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maKhachHang.getText()) : -1;
            if (indexKhachHang >= 0) {
                try {
                    khachHangDAO.xoa(maKhachHang);
                    loadKhachHang();
                    if(temp_indexKhachHang == 0) tbl_KhachHang.setRowSelectionInterval(0, 0);
                    else tbl_KhachHang.setRowSelectionInterval(temp_indexKhachHang-1, temp_indexKhachHang-1);
                    
                } catch(IllegalArgumentException iea){
                } catch (Exception e4){
                    System.out.println(e4);
                }
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (checkValidate()) {
            if (!isUpdate) {
                try {
                    khachHangDAO.them(tenKhachHang, gioiTinh, soDienThoai, ghiChu);
                    loadKhachHang();
                    tbl_KhachHang.setRowSelectionInterval(modelKhachHang.getRowCount()-1, modelKhachHang.getRowCount()-1);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi thêm khách hàng");
                    System.out.println(e);
                }
            } else {
                try {
                    khachHangDAO.sua(maKhachHang, tenKhachHang, gioiTinh, soDienThoai, ghiChu);
                    loadKhachHang();
                    tbl_KhachHang.clearSelection();
                    tbl_KhachHang.setRowSelectionInterval(temp_indexKhachHang, temp_indexKhachHang);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi sửa khách hàng");
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_boquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boquaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
        isUpdate = false;
        try {
            tbl_KhachHang.clearSelection();
            tbl_KhachHang.setRowSelectionInterval(temp_indexKhachHang, temp_indexKhachHang);
        } catch (Exception e) {}
    }//GEN-LAST:event_btn_boquaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String text = txt_timKiem.getText().trim();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập dữ liệu tìm kiếm");
            
        } else {
            listKhachHang.clear();
            modelKhachHang.setRowCount(0);
            listKhachHang = khachHangDAO.timKiem(text);
            listKhachHang.forEach(khachHang -> {
                Vector row = new Vector();
                row.add(khachHang.getMaKhachHang());
                row.add(khachHang.getTenKhachHang());
                row.add(khachHang.isGioiTinh()==true?"Nam":"Nữ");
                row.add(khachHang.getSoDienThoai());
                row.add(khachHang.getGhiChu());
                modelKhachHang.addRow(row);
            });
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void rdo_namFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdo_namFocusGained
        // TODO add your handling code here:
        temp_rdo_nam = rdo_nam.isSelected();
    }//GEN-LAST:event_rdo_namFocusGained

    private void rdo_nuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdo_nuFocusGained
        // TODO add your handling code here:
        temp_rdo_nam = !rdo_nu.isSelected();
    }//GEN-LAST:event_rdo_nuFocusGained

    private void rdo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_namActionPerformed
        // TODO add your handling code here:
        if (!isEditable && !temp_rdo_nam) rdo_nu.setSelected(true);
    }//GEN-LAST:event_rdo_namActionPerformed

    private void rdo_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_nuActionPerformed
        // TODO add your handling code here:
        if (!isEditable && temp_rdo_nam) rdo_nam.setSelected(true);
    }//GEN-LAST:event_rdo_nuActionPerformed

    private void btn_lamMoiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiDanhSachActionPerformed
        // TODO add your handling code here:
        loadKhachHang();
    }//GEN-LAST:event_btn_lamMoiDanhSachActionPerformed

    private boolean checkValidate() {
        maKhachHang = txt_maKhachHang.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maKhachHang.getText()) : -1;
        tenKhachHang = txt_tenKhachHang.getText().trim();
        gioiTinh = rdo_nam.isSelected();
        soDienThoai = txt_soDienThoai.getText().trim();
        ghiChu = txt_ghiChu.getText().trim();
        
        if(tenKhachHang.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Tên khách hàng");
            txt_tenKhachHang.requestFocus();
            return false;
        }
        if(soDienThoai.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Số ĐT");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(tenKhachHang.length()>50){
            JOptionPane.showMessageDialog(this, "Tên khách hàng phải nhỏ hơn 50 kí tự");
            txt_tenKhachHang.requestFocus();
            return false;
        }
        if(!soDienThoai.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Số ĐT không hợp lệ");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(soDienThoai.length()<8 || soDienThoai.length()>10){
            JOptionPane.showMessageDialog(this, "Nhập số điện thoại có độ dài từ 8 đến 10 kí tự");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(ghiChu.length()>100){
            JOptionPane.showMessageDialog(this, "Ghi chú phải nhỏ hơn 100 kí tự");
            txt_ghiChu.requestFocus();
            return false;
        }
        return true;
    }
    
    private void setEditable(boolean isEditable) {
            this.isEditable = isEditable;

            btn_them.setEnabled(!isEditable);
            btn_sua.setEnabled(!isEditable);
            btn_xoa.setEnabled(!isEditable);
            btn_luu.setEnabled(isEditable);
            btn_boqua.setEnabled(isEditable);
            btn_timkiem.setEnabled(!isEditable);

            txt_tenKhachHang.setEditable(isEditable);
            txt_soDienThoai.setEditable(isEditable);
            txt_ghiChu.setEditable(isEditable);

//            if (isEditable) {
//                cbo_.setModel(model_cbo_);
//                cbo_.setModel(model_cbo_);
//            }
    }
    
    DefaultTableModel modelKhachHang = new DefaultTableModel();
    
    List<KhachHang> listKhachHang = new ArrayList<>();
    
    KhachHangDAO khachHangDAO = new KhachHangDAO();
    
    int indexKhachHang = -1;
    int temp_indexKhachHang = -1;

    boolean isEditable = false;
    boolean isUpdate = false;
    
    private int maKhachHang;
    private String tenKhachHang;
    private boolean gioiTinh;
    private String soDienThoai;
    private String ghiChu;
    boolean temp_rdo_nam;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_boqua;
    private javax.swing.JButton btn_lamMoiDanhSach;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup grp_gioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tbl_KhachHang;
    private javax.swing.JTextArea txt_ghiChu;
    private javax.swing.JTextField txt_maKhachHang;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_tenKhachHang;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
