package view;

import dao.KhachHangDAO;
import dao.NhanVienDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.NhanVien;

/**
 *
 * @author Hoang
 */
public class Panel_ThongTinCaNhan extends javax.swing.JPanel {

    /**
     * Creates new form panel_san_pham
     */
    public Panel_ThongTinCaNhan() {
        initComponents();
    }

    public void setdata(){
        loadThongTinCaNhan();
    }
    
    public void loadThongTinCaNhan(){
        NhanVien nhanVien = nhanVienDAO.getNhanVienById(TrangChu.taiKhoan);
        txt_taiKhoan.setText(nhanVien.getTaiKhoan());
        txt_tenNhanVien.setText(nhanVien.getHoTen());
        txt_ngaySinh.setText(format.format(nhanVien.getNgaySinh()));
        txt_gioiTinh.setText(nhanVien.isGioiTinh()==true?"Nam":"Nữ");
        txt_chucVu.setText(nhanVien.getChucVu().getTenChucVu());
        txt_diaChi.setText(nhanVien.getDiaChi());
        txt_email.setText(nhanVien.getEmail());
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_doiMatKhau = new javax.swing.JButton();
        txt_taiKhoan = new javax.swing.JLabel();
        txt_tenNhanVien = new javax.swing.JLabel();
        txt_ngaySinh = new javax.swing.JLabel();
        txt_gioiTinh = new javax.swing.JLabel();
        txt_chucVu = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JLabel();
        txt_email = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Tài Khoản");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Họ Tên");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Ngày Sinh");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Giới Tính");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Chức Vụ");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Địa Chỉ");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Email");

        btn_doiMatKhau.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_doiMatKhau.setText("Đổi Mật Khẩu");
        btn_doiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doiMatKhauActionPerformed(evt);
            }
        });

        txt_taiKhoan.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_taiKhoan.setForeground(java.awt.Color.blue);
        txt_taiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_taiKhoan.setText("jLabel5");

        txt_tenNhanVien.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_tenNhanVien.setForeground(java.awt.Color.blue);
        txt_tenNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tenNhanVien.setText("jLabel5");

        txt_ngaySinh.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_ngaySinh.setForeground(java.awt.Color.blue);
        txt_ngaySinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_ngaySinh.setText("jLabel5");

        txt_gioiTinh.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_gioiTinh.setForeground(java.awt.Color.blue);
        txt_gioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_gioiTinh.setText("jLabel5");

        txt_chucVu.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_chucVu.setForeground(java.awt.Color.blue);
        txt_chucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_chucVu.setText("jLabel5");

        txt_diaChi.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_diaChi.setForeground(java.awt.Color.blue);
        txt_diaChi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_diaChi.setText("jLabel5");

        txt_email.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_email.setForeground(java.awt.Color.blue);
        txt_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_email.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_doiMatKhau)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(970, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_doiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_doiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doiMatKhauActionPerformed
        // TODO add your handling code here:
        new Popup_DoiMatKhau(false).setVisible(true);
    }//GEN-LAST:event_btn_doiMatKhauActionPerformed

    NhanVienDAO nhanVienDAO = new NhanVienDAO();
    SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    protected static javax.swing.JLabel txt_chucVu;
    protected static javax.swing.JLabel txt_diaChi;
    protected static javax.swing.JLabel txt_email;
    protected static javax.swing.JLabel txt_gioiTinh;
    protected static javax.swing.JLabel txt_ngaySinh;
    protected static javax.swing.JLabel txt_taiKhoan;
    protected static javax.swing.JLabel txt_tenNhanVien;
    // End of variables declaration//GEN-END:variables
}
