package view;

import dao.ChucVuDAO;
import dao.NhanVienDAO;
import java.awt.Font;
import java.awt.Window;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.NhanVien;

/**
 *
 * @author Hoang
 */
public class Panel_NhanVien extends javax.swing.JPanel {

    /**
     * Creates new form panel_san_pham
     */
    public Panel_NhanVien() {
        initComponents();
    }

    public void setdata(){
        modelNhanVien.addColumn("Tài Khoản");
        modelNhanVien.addColumn("Họ Tên");
        modelNhanVien.addColumn("Ngày Sinh");
        modelNhanVien.addColumn("Giới Tính");
        modelNhanVien.addColumn("Ngày Vào Làm");
        modelNhanVien.addColumn("Chức Vụ");
        modelNhanVien.addColumn("Địa Chỉ");
        modelNhanVien.addColumn("Số ĐT");
        modelNhanVien.addColumn("Email");
        modelNhanVien.addColumn("Ghi Chú");
        
        cbo_chucVu.setModel(modelChucVu);
        tbl_NhanVien.setModel(modelNhanVien);
        
        tbl_NhanVien.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexNhanVien = tbl_NhanVien.getSelectedRow();
            if(indexNhanVien>=0 && !isEditable){
                txt_taiKhoan.setText(tbl_NhanVien.getValueAt(indexNhanVien, 0).toString());
                txt_hoTen.setText(tbl_NhanVien.getValueAt(indexNhanVien, 1).toString());
                txt_ngaySinh.setText(tbl_NhanVien.getValueAt(indexNhanVien, 2).toString());
                if(tbl_NhanVien.getValueAt(indexNhanVien, 3).toString().equals("Nam")) rdo_nam.setSelected(true);
                else rdo_nu.setSelected(true);
                txt_ngayVaoLam.setText(tbl_NhanVien.getValueAt(indexNhanVien, 4).toString());
                cbo_chucVu.setModel(new DefaultComboBoxModel<>(new String[]{tbl_NhanVien.getValueAt(indexNhanVien, 5).toString()}));
                txt_diaChi.setText(tbl_NhanVien.getValueAt(indexNhanVien, 6).toString());
                txt_soDienThoai.setText(tbl_NhanVien.getValueAt(indexNhanVien, 7).toString());
                txt_email.setText(tbl_NhanVien.getValueAt(indexNhanVien, 8).toString());
                txt_ghiChu.setText(tbl_NhanVien.getValueAt(indexNhanVien, 4)==null?"":tbl_NhanVien.getValueAt(indexNhanVien, 4).toString());
                
            } else if (isUpdate){
                
            } else if (isEditable){
                
            }
        });
        
        loadNhanVien();
        
        setEditable(false);
        txt_taiKhoan.setEditable(false);
        try {
            if(modelNhanVien.getRowCount()>0) tbl_NhanVien.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }
    
    public void loadNhanVien(){
        setEditable(false);
        isUpdate = false;
        listNhanVien.clear();
        modelNhanVien.setRowCount(0);
        
        listNhanVien = nhanVienDAO.getList();
        listNhanVien.forEach(nhanVien -> {
            Vector row = new Vector();
            row.add(nhanVien.getTaiKhoan());
            row.add(nhanVien.getHoTen());
            row.add(format.format(nhanVien.getNgaySinh()));
            row.add(nhanVien.isGioiTinh()==true?"Nam":"Nữ");
            row.add(format.format(nhanVien.getNgayVaoLam()));
            row.add(nhanVien.getChucVu().getTenChucVu());
            row.add(nhanVien.getDiaChi());
            row.add(nhanVien.getSoDienThoai());
            row.add(nhanVien.getEmail());
            row.add(nhanVien.getGhiChu());
            modelNhanVien.addRow(row);
        });
        
        listChucVu.clear();
        modelChucVu.removeAllElements();
        modelChucVu.addElement("-- Chọn Chức Vụ--");
        listChucVu = chucVuDAO.getListChucVu();
        
        maChucVu = nhanVienDAO.getNhanVienById(TrangChu.taiKhoan).getChucVu().getMaChucVu();
        listChucVu.forEach((chucVu) -> {
            if(maChucVu==1){
                modelChucVu.addElement(chucVu.getTenChucVu());
            } else if (chucVu.getMaChucVu()!=1){
                modelChucVu.addElement(chucVu.getTenChucVu());
            }
        });
        
        if(modelNhanVien.getRowCount()>0){
            try {
                tbl_NhanVien.setRowSelectionInterval(0, 0);
            } catch (Exception e) {}
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_gioiTinh = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhanVien = new javax.swing.JTable();
        txt_hoTen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_boqua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        txt_taiKhoan = new javax.swing.JTextField();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        txt_ngaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ngayVaoLam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbo_chucVu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();

        tbl_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tài Khoản", "Họ Tên", "Ngày Sinh", "Giới Tính", "Ngày Vào Làm", "Chức Vụ", "Địa Chỉ", "Số ĐT", "Email", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tbl_NhanVien);

        jLabel1.setText("Tài Khoản");

        jLabel2.setText("Họ Tên");

        btn_boqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/boqua.png"))); // NOI18N
        btn_boqua.setText("Bỏ Qua");
        btn_boqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boquaActionPerformed(evt);
            }
        });

        jLabel3.setText("Ngày Sinh");

        jLabel4.setText("Giới Tính");

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChu);

        jLabel8.setText("Ghi Chú");

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_them.setText("Tạo Mới");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/sua.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/xoa.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/timkiem.png"))); // NOI18N
        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timkiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grp_gioiTinh.add(rdo_nam);
        rdo_nam.setText("Nam");
        rdo_nam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdo_namFocusGained(evt);
            }
        });
        rdo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_namActionPerformed(evt);
            }
        });

        grp_gioiTinh.add(rdo_nu);
        rdo_nu.setText("Nữ");
        rdo_nu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdo_nuFocusGained(evt);
            }
        });
        rdo_nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_nuActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày Vào Làm");

        jLabel6.setText("Chức Vụ");

        cbo_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Địa Chỉ");

        jLabel9.setText("Số ĐT");

        jLabel10.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_hoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txt_taiKhoan)
                            .addComponent(txt_ngaySinh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdo_nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdo_nu))
                            .addComponent(txt_ngayVaoLam))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(cbo_chucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_diaChi)
                            .addComponent(txt_soDienThoai)
                            .addComponent(txt_email))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_boqua, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 358, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbo_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_nam)
                    .addComponent(rdo_nu)
                    .addComponent(jLabel10)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_boqua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_ngayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        temp_indexNhanVien = indexNhanVien;
        setEditable(true);
        txt_taiKhoan.setText("");
        txt_hoTen.requestFocus();
        txt_hoTen.setText("");
        txt_ngaySinh.setText("");
        rdo_nam.setSelected(true);
        txt_ngayVaoLam.setText(format.format(new java.util.Date()));
        cbo_chucVu.setSelectedIndex(0);
        txt_diaChi.setText("");
        txt_soDienThoai.setText("");
        txt_email.setText("");
        txt_ghiChu.setText("");
        tbl_NhanVien.clearSelection();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        temp_indexNhanVien = indexNhanVien;
        String chucVu = cbo_chucVu.getSelectedItem().toString();
        setEditable(true);
        isUpdate = true;
        txt_hoTen.requestFocus();
        cbo_chucVu.setSelectedItem(chucVu);
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        temp_indexNhanVien = indexNhanVien;
        taiKhoan = txt_taiKhoan.getText().trim();
        ChucVu chucVu = nhanVienDAO.getNhanVienById(taiKhoan).getChucVu();
        JLabel confirm = new JLabel("Xác nhận xóa "+ chucVu.getTenChucVu()+" "+txt_hoTen.getText()+"?");
        confirm.setFont(new Font("Dialog", Font.PLAIN, 14));
        int a = JOptionPane.showConfirmDialog(this, confirm, "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == JOptionPane.YES_OPTION) {
            
            if(chucVu.getMaChucVu()==1 && nhanVienDAO.countGiamDoc()==1){
                JOptionPane.showMessageDialog(this, "Phải có 1 " + chucVu.getTenChucVu());
                
            } else if (indexNhanVien >= 0) {
                try {
                    nhanVienDAO.xoa(taiKhoan);
                    loadNhanVien();
                    if(temp_indexNhanVien == 0) tbl_NhanVien.setRowSelectionInterval(0, 0);
                    else tbl_NhanVien.setRowSelectionInterval(temp_indexNhanVien-1, temp_indexNhanVien-1);
                    if(taiKhoan.equals(TrangChu.taiKhoan)){
                        JOptionPane.showMessageDialog(this, "Hết phiên đăng nhập");
                        setVisible(false);
                        ((Window) getRootPane().getParent()).dispose();
                        new DangNhap().setVisible(true);
                    }
                    
                    
                } catch(IllegalArgumentException iea){
                } catch (Exception e4){
                    System.out.println(e4);
                }
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (checkValidate()) {
            if (!isUpdate) {
                try {
                    nhanVienDAO.them(hoTen, ngaySinh, gioiTinh, ngayVaoLam, maChucVu, diaChi, soDienThoai, email, ghiChu);
                    loadNhanVien();
                    tbl_NhanVien.setRowSelectionInterval(modelNhanVien.getRowCount()-1, modelNhanVien.getRowCount()-1);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi thêm nhân viên");
                    System.out.println(e);
                }
            } else {
                try {
                    nhanVienDAO.sua(taiKhoan, hoTen, ngaySinh, gioiTinh, ngayVaoLam, maChucVu, diaChi, soDienThoai, email, ghiChu);
                    loadNhanVien();
                    tbl_NhanVien.clearSelection();
                    tbl_NhanVien.setRowSelectionInterval(temp_indexNhanVien, temp_indexNhanVien);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi sửa nhân viên");
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_boquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boquaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
        isUpdate = false;
        try {
            tbl_NhanVien.clearSelection();
            tbl_NhanVien.setRowSelectionInterval(temp_indexNhanVien, temp_indexNhanVien);
        } catch (Exception e) {}
    }//GEN-LAST:event_btn_boquaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void rdo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_namActionPerformed
        // TODO add your handling code here:
        if (!isEditable && !temp_rdo_nam) rdo_nu.setSelected(true);
    }//GEN-LAST:event_rdo_namActionPerformed

    private void rdo_nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_nuActionPerformed
        // TODO add your handling code here:
        if (!isEditable && temp_rdo_nam) rdo_nam.setSelected(true);
    }//GEN-LAST:event_rdo_nuActionPerformed

    private void rdo_namFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdo_namFocusGained
        // TODO add your handling code here:
        temp_rdo_nam = rdo_nam.isSelected();
    }//GEN-LAST:event_rdo_namFocusGained

    private void rdo_nuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdo_nuFocusGained
        // TODO add your handling code here:
        temp_rdo_nam = !rdo_nu.isSelected();
    }//GEN-LAST:event_rdo_nuFocusGained

    public boolean checkValidate() {
        taiKhoan = txt_taiKhoan.getText().trim();
        hoTen = txt_hoTen.getText().trim();
        ngaySinh = txt_ngaySinh.getText().trim();
        gioiTinh = rdo_nam.isSelected();
        ngayVaoLam = txt_ngayVaoLam.getText().trim();
        if(cbo_chucVu.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Chưa chọn Chức vụ");
            cbo_chucVu.requestFocus();
            return false;
        }
        maChucVu = listChucVu.stream().filter(chucvu -> (cbo_chucVu.getSelectedItem().toString().equals(chucvu.getTenChucVu()))).findAny().orElse(null).getMaChucVu();
        diaChi = txt_diaChi.getText().trim();
        soDienThoai = txt_soDienThoai.getText().trim();
        email = txt_email.getText().trim();
        ghiChu = txt_ghiChu.getText().trim();
        
        if(hoTen.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Tên nhân viên");
            txt_hoTen.requestFocus();
            return false;
        }
        if(ngaySinh.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Ngày sinh");
            txt_ngaySinh.requestFocus();
            return false;
        }
        if(ngayVaoLam.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Ngày vào làm");
            txt_ngayVaoLam.requestFocus();
            return false;
        }
        if(diaChi.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Địa Chỉ");
            txt_diaChi.requestFocus();
            return false;
        }
        if(soDienThoai.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Số ĐT");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(email.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Email");
            txt_email.requestFocus();
            return false;
        }
        if(hoTen.length()>50){
            JOptionPane.showMessageDialog(this, "Họ tên phải nhỏ hơn 50 kí tự");
            txt_hoTen.requestFocus();
            return false;
        }
        
        if(!ngaySinh.matches(reg1) && !ngaySinh.matches(reg2)){
            JOptionPane.showMessageDialog(this, "Ngày sinh không đúng định dạng dd-MM-yyyy");
            txt_ngaySinh.requestFocus();
            return false;
            
        }  else {
            if(ngaySinh.matches(reg2)){
                ngaySinh = ngaySinh.replace("/", "-");
            }
                
            int day = Integer.valueOf(ngaySinh.substring(0, ngaySinh.indexOf("-")));
            int month = Integer.valueOf(ngaySinh.substring(ngaySinh.indexOf("-")+1, ngaySinh.lastIndexOf("-")));
            int year = Integer.valueOf(ngaySinh.substring(ngaySinh.lastIndexOf("-")+1, ngaySinh.length()));

            try {
                String ngaysinh2 = format.format(format.parse(ngaySinh));
                int day2 = Integer.valueOf(ngaysinh2.substring(0, ngaysinh2.indexOf("-")));
                int month2 = Integer.valueOf(ngaysinh2.substring(ngaysinh2.indexOf("-")+1, ngaysinh2.lastIndexOf("-")));
                int year2 = Integer.valueOf(ngaysinh2.substring(ngaysinh2.lastIndexOf("-")+1, ngaysinh2.length()));

                if(day!=day2 || month!=month2 || year!=year2){
                    JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ: Không có ngày "+ngaySinh);
                    txt_ngaySinh.requestFocus();
                    return false;
                }
                if(new Date().compareTo(format.parse(ngaySinh))==-1){
                    JOptionPane.showMessageDialog(this, "Ngày sinh lớn hơn ngày hiện tại (" +format.format(new Date())+")");
                    txt_ngaySinh.requestFocus();
                    return false;
                }
                
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không đúng định dạng dd-MM-yyyy");
                txt_ngaySinh.requestFocus();
                return false;
            }
        }
        
        if(!ngayVaoLam.matches(reg1) && !ngayVaoLam.matches(reg2)){
            JOptionPane.showMessageDialog(this, "Ngày vào làm không đúng định dạng dd-MM-yyyy");
            txt_ngayVaoLam.requestFocus();
            return false;
            
        }  else {
            if(ngayVaoLam.matches(reg2)){
                ngayVaoLam = ngayVaoLam.replace("/", "-");
            }
                
            int day = Integer.valueOf(ngayVaoLam.substring(0, ngayVaoLam.indexOf("-")));
            int month = Integer.valueOf(ngayVaoLam.substring(ngayVaoLam.indexOf("-")+1, ngayVaoLam.lastIndexOf("-")));
            int year = Integer.valueOf(ngayVaoLam.substring(ngayVaoLam.lastIndexOf("-")+1, ngayVaoLam.length()));

            try {
                String ngaysinh2 = format.format(format.parse(ngayVaoLam));
                int day2 = Integer.valueOf(ngaysinh2.substring(0, ngaysinh2.indexOf("-")));
                int month2 = Integer.valueOf(ngaysinh2.substring(ngaysinh2.indexOf("-")+1, ngaysinh2.lastIndexOf("-")));
                int year2 = Integer.valueOf(ngaysinh2.substring(ngaysinh2.lastIndexOf("-")+1, ngaysinh2.length()));

                if(day!=day2 || month!=month2 || year!=year2){
                    JOptionPane.showMessageDialog(this, "Ngày vào làm không hợp lệ: Không có ngày "+ngayVaoLam);
                    txt_ngayVaoLam.requestFocus();
                    return false;
                }
                if(new Date().compareTo(format.parse(ngayVaoLam))==-1){
                    JOptionPane.showMessageDialog(this, "Ngày vào làm lớn hơn ngày hiện tại (" +format.format(new Date())+")");
                    txt_ngayVaoLam.requestFocus();
                    return false;
                }

            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Ngày vào làm không đúng định dạng dd-MM-yyyy");
                txt_ngayVaoLam.requestFocus();
                return false;
            }
        }
        if(diaChi.length()>100){
            JOptionPane.showMessageDialog(this, "Địa chỉ phải nhỏ hơn 100 kí tự");
            txt_diaChi.requestFocus();
            return false;
        }
        if(!soDienThoai.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Số ĐT không hợp lệ");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(soDienThoai.length()<8 || soDienThoai.length()>10){
            JOptionPane.showMessageDialog(this, "Nhập số điện thoại có độ dài từ 8 đến 10 kí tự");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(!email.matches("\\w+@+\\w+.+\\w")){
            JOptionPane.showMessageDialog(this, "Email không hợp lệ");
            txt_email.requestFocus();
            return false;
        }
        if(email.length()>50){
            JOptionPane.showMessageDialog(this, "Email phải nhỏ hơn 50 kí tự");
            txt_email.requestFocus();
            return false;
        }
        if(ghiChu.length()>100){
            JOptionPane.showMessageDialog(this, "Ghi chú phải nhỏ hơn 100 kí tự");
            txt_ghiChu.requestFocus();
            return false;
        }
        return true;
    }
    
    public void setEditable(boolean isEditable) {
            this.isEditable = isEditable;

            btn_them.setEnabled(!isEditable);
            btn_sua.setEnabled(!isEditable);
            btn_xoa.setEnabled(!isEditable);
            btn_luu.setEnabled(isEditable);
            btn_boqua.setEnabled(isEditable);
            btn_timkiem.setEnabled(!isEditable);

            txt_hoTen.setEditable(isEditable);
            txt_ngaySinh.setEditable(isEditable);
            txt_ngayVaoLam.setEditable(isEditable);
            txt_diaChi.setEditable(isEditable);
            txt_soDienThoai.setEditable(isEditable);
            txt_email.setEditable(isEditable);
            txt_ghiChu.setEditable(isEditable);

            if (isEditable) {
                cbo_chucVu.setModel(modelChucVu);
            }
    }
    
    
    SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    
    DefaultTableModel modelNhanVien = new DefaultTableModel();
    DefaultComboBoxModel<String> modelChucVu = new DefaultComboBoxModel<>();
    
    List<NhanVien> listNhanVien = new ArrayList<>();
    List<ChucVu> listChucVu = new ArrayList<>();
    
    NhanVienDAO nhanVienDAO = new NhanVienDAO();
    ChucVuDAO chucVuDAO = new ChucVuDAO();
    
    int indexNhanVien = -1;
    int temp_indexNhanVien = -1;

    boolean isEditable = false;
    boolean isUpdate = false;
    
    String reg1 = "\\d{1,2}-\\d{1,2}-\\d{1,4}";
    String reg2 = "\\d{1,2}/\\d{1,2}/\\d{1,4}";
    
    private String taiKhoan;
    private String hoTen;
    private String ngaySinh;
    private boolean gioiTinh;
    private String ngayVaoLam;
    private int maChucVu;
    private String diaChi;
    private String soDienThoai;
    private String email;
    private String ghiChu;
    boolean temp_rdo_nam;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_boqua;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_chucVu;
    private javax.swing.ButtonGroup grp_gioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tbl_NhanVien;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextArea txt_ghiChu;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_ngaySinh;
    private javax.swing.JTextField txt_ngayVaoLam;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_taiKhoan;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
