package view;

import dao.HangSanXuatDAO;
import dao.LoaiSanPhamDAO;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.HangSanXuat;
import model.LoaiSanPham;

/**
 *
 * @author Hoang
 */
public class Panel_LoaiSP_HangSX extends javax.swing.JPanel {

    /**
     * Creates new form panel_san_pham
     */
    public Panel_LoaiSP_HangSX() {
        initComponents();
    }

    public void setdata(){
        modeLoaiSanPham.addColumn("Mã Loại Sản Phẩm");
        modeLoaiSanPham.addColumn("Tên Loại Sản Phẩm");
        modeLoaiSanPham.addColumn("Ghi Chú");
        modeHangSanXuat.addColumn("Mã Hãng Sản Xuất");
        modeHangSanXuat.addColumn("Tên Hãng Sản Xuất");
        modeHangSanXuat.addColumn("Ghi Chú");
        
        tbl_LoaiSanPham.setModel(modeLoaiSanPham);
        tbl_HangSanXuat.setModel(modeHangSanXuat);
        
        tbl_LoaiSanPham.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexLoaiSanPham = tbl_LoaiSanPham.getSelectedRow();
            if(indexLoaiSanPham>=0 && !isEditableLoaiSanPham){
                txt_maLoaiSanPham.setText(tbl_LoaiSanPham.getValueAt(indexLoaiSanPham, 0).toString());
                txt_tenLoaiSanPham.setText(tbl_LoaiSanPham.getValueAt(indexLoaiSanPham, 1).toString());
                txt_ghiChuLoaiSanPham.setText(tbl_LoaiSanPham.getValueAt(indexLoaiSanPham, 2)==null?"":tbl_LoaiSanPham.getValueAt(indexLoaiSanPham, 2).toString());
            } 
        });
        tbl_HangSanXuat.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexHangSanXuat = tbl_HangSanXuat.getSelectedRow();
            if(indexHangSanXuat>=0 && !isEditableHangSanXuat){
                txt_maHangSanXuat.setText(tbl_HangSanXuat.getValueAt(indexHangSanXuat, 0).toString());
                txt_tenHangSanXuat.setText(tbl_HangSanXuat.getValueAt(indexHangSanXuat, 1).toString());
                txt_ghiChuHangSanXuat.setText(tbl_HangSanXuat.getValueAt(indexHangSanXuat, 2)==null?"":tbl_HangSanXuat.getValueAt(indexHangSanXuat, 2).toString());
            } 
        });
        
        loadLoaiSanPham();
        loadHangSanXuat();
        
        setEditableLoaiSanPham(false);
        setEditableHangSanXuat(false);
        txt_maLoaiSanPham.setEditable(false);
        txt_maHangSanXuat.setEditable(false);
        try {
            if(modeLoaiSanPham.getRowCount()>0) tbl_LoaiSanPham.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
        try {
            if(modeHangSanXuat.getRowCount()>0) tbl_HangSanXuat.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }
    
    public void loadLoaiSanPham(){
        setEditableLoaiSanPham(false);
        isUpdateLoaiSanPham = false;
        listLoaiSanPham.clear();
        modeLoaiSanPham.setRowCount(0);
        
        listLoaiSanPham = loaiSanPhamDAO.getListLoaiSanPham();
        listLoaiSanPham.forEach(loaiSanPham -> {
            Vector row = new Vector();
            row.add(loaiSanPham.getMaLoaiSanPham());
            row.add(loaiSanPham.getTenLoaiSanPham());
            row.add(loaiSanPham.getGhiChu());
            modeLoaiSanPham.addRow(row);
        });
        try {
            if(modeLoaiSanPham.getRowCount()>0) tbl_LoaiSanPham.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }
    
    public void loadHangSanXuat(){
        setEditableHangSanXuat(false);
        isUpdateHangSanXuat = false;
        listHangSanXuat.clear();
        modeHangSanXuat.setRowCount(0);
        
        listHangSanXuat = hangSanXuatDAO.getListHangSanXuat();
        listHangSanXuat.forEach(hangSanXuat -> {
            Vector row = new Vector();
            row.add(hangSanXuat.getMaHangSanXuat());
            row.add(hangSanXuat.getTenHangSanXuat());
            row.add(hangSanXuat.getGhiChu());
            modeHangSanXuat.addRow(row);
        });
        try {
            if(modeHangSanXuat.getRowCount()>0) tbl_HangSanXuat.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_LoaiSanPham = new javax.swing.JTable();
        txt_tenLoaiSanPham = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_boquaLoaiSanPham = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChuLoaiSanPham = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btn_themLoaiSanPham = new javax.swing.JButton();
        txt_maLoaiSanPham = new javax.swing.JTextField();
        btn_suaLoaiSanPham = new javax.swing.JButton();
        btn_xoaLoaiSanPham = new javax.swing.JButton();
        btn_luuLoaiSanPham = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_HangSanXuat = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_ghiChuHangSanXuat = new javax.swing.JTextArea();
        btn_boquaHangSanXuat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tenHangSanXuat = new javax.swing.JTextField();
        btn_luuHangSanXuat = new javax.swing.JButton();
        btn_xoaHangSanXuat = new javax.swing.JButton();
        btn_suaHangSanXuat = new javax.swing.JButton();
        txt_maHangSanXuat = new javax.swing.JTextField();
        btn_themHangSanXuat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        tbl_LoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Loại Sản Phẩm", "Tên Loại Sản Phẩm", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tbl_LoaiSanPham);

        jLabel1.setText("Mã Loại Sản Phẩm");

        jLabel2.setText("Tên Loại Sản Phẩm");

        btn_boquaLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/boqua.png"))); // NOI18N
        btn_boquaLoaiSanPham.setText("Bỏ Qua");
        btn_boquaLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boquaLoaiSanPhamActionPerformed(evt);
            }
        });

        txt_ghiChuLoaiSanPham.setColumns(20);
        txt_ghiChuLoaiSanPham.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChuLoaiSanPham);

        jLabel8.setText("Ghi Chú");

        btn_themLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_themLoaiSanPham.setText("Tạo Mới");
        btn_themLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themLoaiSanPhamActionPerformed(evt);
            }
        });

        btn_suaLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/sua.png"))); // NOI18N
        btn_suaLoaiSanPham.setText("Sửa Loại SP");
        btn_suaLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaLoaiSanPhamActionPerformed(evt);
            }
        });

        btn_xoaLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/xoa.png"))); // NOI18N
        btn_xoaLoaiSanPham.setText("Xóa Loại SP");
        btn_xoaLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaLoaiSanPhamActionPerformed(evt);
            }
        });

        btn_luuLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luuLoaiSanPham.setText("Lưu Loại SP");
        btn_luuLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuLoaiSanPhamActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("QUẢN LÝ LOẠI SẢN PHẨM");

        tbl_HangSanXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Nhà Sản Xuất", "Tên Nhà Sản Xuất", "Ghi Chú"
            }
        ));
        jScrollPane3.setViewportView(tbl_HangSanXuat);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("QUẢN LÝ HÃNG SẢN XUẤT");

        txt_ghiChuHangSanXuat.setColumns(20);
        txt_ghiChuHangSanXuat.setRows(5);
        jScrollPane4.setViewportView(txt_ghiChuHangSanXuat);

        btn_boquaHangSanXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/boqua.png"))); // NOI18N
        btn_boquaHangSanXuat.setText("Bỏ Qua");
        btn_boquaHangSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boquaHangSanXuatActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên Loại Sản Phẩm");

        jLabel4.setText("Mã Loại Sản Phẩm");

        btn_luuHangSanXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luuHangSanXuat.setText("Lưu Hãng SX");
        btn_luuHangSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuHangSanXuatActionPerformed(evt);
            }
        });

        btn_xoaHangSanXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/xoa.png"))); // NOI18N
        btn_xoaHangSanXuat.setText("Xóa Hãng SX");
        btn_xoaHangSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaHangSanXuatActionPerformed(evt);
            }
        });

        btn_suaHangSanXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/sua.png"))); // NOI18N
        btn_suaHangSanXuat.setText("Sửa Hãng SX");
        btn_suaHangSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaHangSanXuatActionPerformed(evt);
            }
        });

        btn_themHangSanXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_themHangSanXuat.setText("Tạo Mới");
        btn_themHangSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themHangSanXuatActionPerformed(evt);
            }
        });

        jLabel9.setText("Ghi Chú");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(204, 204, 204))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_tenLoaiSanPham)
                    .addComponent(txt_maLoaiSanPham)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_suaLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luuLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_boquaLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel9))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_tenHangSanXuat)
                    .addComponent(txt_maHangSanXuat)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_themHangSanXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_xoaHangSanXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_suaHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_boquaHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_luuHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_maLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_themLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tenLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_suaLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_xoaLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(btn_luuLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_boquaLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_maHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_themHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_tenHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_suaHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_xoaHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addComponent(btn_luuHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_boquaHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        temp_indexLoaiSanPham = indexLoaiSanPham;
        setEditableLoaiSanPham(true);
        txt_maLoaiSanPham.setText("");
        txt_tenLoaiSanPham.requestFocus();
        txt_tenLoaiSanPham.setText("");
        txt_ghiChuLoaiSanPham.setText("");
        tbl_LoaiSanPham.clearSelection();
    }//GEN-LAST:event_btn_themLoaiSanPhamActionPerformed

    private void btn_suaLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        temp_indexLoaiSanPham = indexLoaiSanPham;
        setEditableLoaiSanPham(true);
        isUpdateLoaiSanPham = true;
        txt_tenLoaiSanPham.requestFocus();
    }//GEN-LAST:event_btn_suaLoaiSanPhamActionPerformed

    private void btn_xoaLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        temp_indexLoaiSanPham = indexLoaiSanPham;
        JLabel confirm = new JLabel("Xác nhận xóa loại sản phẩm "+txt_tenLoaiSanPham.getText()+"?");
        confirm.setFont(new Font("Dialog", Font.PLAIN, 17));
        int a = JOptionPane.showConfirmDialog(this, confirm, "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == JOptionPane.YES_OPTION) {
            maLoaiSanPham = txt_maLoaiSanPham.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maLoaiSanPham.getText()) : -1;
            if (indexLoaiSanPham >= 0) {
                try {
                    if(!loaiSanPhamDAO.xoa(maLoaiSanPham)){
                        JOptionPane.showMessageDialog(this, "Không thể xóa Loại sản phẩm đang có sản phẩm");
                        
                    } else {
                        loadLoaiSanPham();
                        if(temp_indexLoaiSanPham == 0) tbl_LoaiSanPham.setRowSelectionInterval(0, 0);
                        else tbl_LoaiSanPham.setRowSelectionInterval(temp_indexLoaiSanPham-1, temp_indexLoaiSanPham-1);
                    }
                    
                } catch(IllegalArgumentException iea){
                } catch (Exception e4){
                    System.out.println(e4);
                }
            }
        }
    }//GEN-LAST:event_btn_xoaLoaiSanPhamActionPerformed

    private void btn_luuLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        if (checkValidateLoaiSanPham()) {
            if (!isUpdateLoaiSanPham) {
                try {
                    loaiSanPhamDAO.them(tenLoaiSanPham, ghiChuLoaiSanPham);
                    loadLoaiSanPham();
                    tbl_LoaiSanPham.setRowSelectionInterval(modeLoaiSanPham.getRowCount()-1, modeLoaiSanPham.getRowCount()-1);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi thêm loại sản phẩm");
                    System.out.println(e);
                }
            } else {
                try {
                    loaiSanPhamDAO.sua(maLoaiSanPham, tenLoaiSanPham, ghiChuLoaiSanPham);
                    loadLoaiSanPham();
                    tbl_LoaiSanPham.clearSelection();
                    tbl_LoaiSanPham.setRowSelectionInterval(temp_indexLoaiSanPham, temp_indexLoaiSanPham);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi sửa loại sản phẩm");
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_btn_luuLoaiSanPhamActionPerformed

    private void btn_boquaLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boquaLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        setEditableLoaiSanPham(false);
        isUpdateLoaiSanPham = false;
        try {
            tbl_LoaiSanPham.clearSelection();
            tbl_LoaiSanPham.setRowSelectionInterval(temp_indexLoaiSanPham, temp_indexLoaiSanPham);
        } catch (Exception e) {}
    }//GEN-LAST:event_btn_boquaLoaiSanPhamActionPerformed

    private void btn_boquaHangSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boquaHangSanXuatActionPerformed
        // TODO add your handling code here:
        setEditableHangSanXuat(false);
        isUpdateHangSanXuat = false;
        try {
            tbl_HangSanXuat.clearSelection();
            tbl_HangSanXuat.setRowSelectionInterval(temp_indexHangSanXuat, temp_indexHangSanXuat);
        } catch (Exception e) {}
    }//GEN-LAST:event_btn_boquaHangSanXuatActionPerformed

    private void btn_luuHangSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuHangSanXuatActionPerformed
        // TODO add your handling code here:
        if (checkValidateHangSanXuat()) {
            if (!isUpdateHangSanXuat) {
                try {
                    hangSanXuatDAO.them(tenHangSanXuat, ghiChuHangSanXuat);
                    loadHangSanXuat();
                    tbl_HangSanXuat.setRowSelectionInterval(modeHangSanXuat.getRowCount()-1, modeHangSanXuat.getRowCount()-1);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi thêm hãng sản xuất");
                    System.out.println(e);
                }
            } else {
                try {
                    hangSanXuatDAO.sua(maHangSanXuat, tenHangSanXuat, ghiChuHangSanXuat);
                    loadHangSanXuat();
                    tbl_HangSanXuat.clearSelection();
                    tbl_HangSanXuat.setRowSelectionInterval(temp_indexHangSanXuat, temp_indexHangSanXuat);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi sửa hãng sản xuất");
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_btn_luuHangSanXuatActionPerformed

    private void btn_xoaHangSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaHangSanXuatActionPerformed
        // TODO add your handling code here:
        temp_indexHangSanXuat = indexHangSanXuat;
        JLabel confirm = new JLabel("Xác nhận xóa hãng sản xuất "+txt_tenHangSanXuat.getText()+"?");
        confirm.setFont(new Font("Dialog", Font.PLAIN, 17));
        int a = JOptionPane.showConfirmDialog(this, confirm, "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == JOptionPane.YES_OPTION) {
            maHangSanXuat = txt_maHangSanXuat.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maHangSanXuat.getText()) : -1;
            if (indexHangSanXuat >= 0) {
                try {
                    if(!hangSanXuatDAO.xoa(maHangSanXuat)){
                        JOptionPane.showMessageDialog(this, "Không thể xóa Hãng sản xuất đang có sản phẩm");
                        
                    } else {
                        loadHangSanXuat();
                        if(temp_indexHangSanXuat == 0) tbl_HangSanXuat.setRowSelectionInterval(0, 0);
                        else tbl_HangSanXuat.setRowSelectionInterval(temp_indexHangSanXuat-1, temp_indexHangSanXuat-1);
                    }
                    
                } catch(IllegalArgumentException iea){
                } catch (Exception e4){
                    System.out.println(e4);
                }
            }
        }
    }//GEN-LAST:event_btn_xoaHangSanXuatActionPerformed

    private void btn_suaHangSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaHangSanXuatActionPerformed
        // TODO add your handling code here:
        temp_indexHangSanXuat = indexHangSanXuat;
        setEditableHangSanXuat(true);
        isUpdateHangSanXuat = true;
        txt_tenHangSanXuat.requestFocus();
    }//GEN-LAST:event_btn_suaHangSanXuatActionPerformed

    private void btn_themHangSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themHangSanXuatActionPerformed
        // TODO add your handling code here:
        temp_indexHangSanXuat = indexHangSanXuat;
        setEditableHangSanXuat(true);
        txt_maHangSanXuat.setText("");
        txt_tenHangSanXuat.requestFocus();
        txt_tenHangSanXuat.setText("");
        txt_ghiChuHangSanXuat.setText("");
        tbl_HangSanXuat.clearSelection();
    }//GEN-LAST:event_btn_themHangSanXuatActionPerformed

    private boolean checkValidateLoaiSanPham() {
        maLoaiSanPham = txt_maLoaiSanPham.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maLoaiSanPham.getText()) : -1;
        tenLoaiSanPham = txt_tenLoaiSanPham.getText().trim();
        ghiChuLoaiSanPham = txt_ghiChuLoaiSanPham.getText().trim();
        
        if(tenLoaiSanPham.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Tên loại sản phẩm");
            txt_tenLoaiSanPham.requestFocus();
            return false;
        }
        if(tenLoaiSanPham.length()>50){
            JOptionPane.showMessageDialog(this, "Tên loại sản phẩm phải nhỏ hơn 50 kí tự");
            txt_tenLoaiSanPham.requestFocus();
            return false;
        }
        if(ghiChuLoaiSanPham.length()>100){
            JOptionPane.showMessageDialog(this, "Ghi chú phải nhỏ hơn 100 kí tự");
            txt_ghiChuLoaiSanPham.requestFocus();
            return false;
        }
        
        return true;
    }
    
    private boolean checkValidateHangSanXuat() {
        maHangSanXuat = txt_maHangSanXuat.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maHangSanXuat.getText()) : -1;
        tenHangSanXuat = txt_tenHangSanXuat.getText().trim();
        ghiChuHangSanXuat = txt_ghiChuHangSanXuat.getText().trim();
        
        if(tenHangSanXuat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Tên Hãng sản xuất");
            txt_tenHangSanXuat.requestFocus();
            return false;
        }
        if(tenHangSanXuat.length()>50){
            JOptionPane.showMessageDialog(this, "Tên Hãng sản xuất phải nhỏ hơn 50 kí tự");
            txt_tenHangSanXuat.requestFocus();
            return false;
        }
        if(ghiChuHangSanXuat.length()>100){
            JOptionPane.showMessageDialog(this, "Ghi chú phải nhỏ hơn 100 kí tự");
            txt_ghiChuHangSanXuat.requestFocus();
            return false;
        }
        
        return true;
    }
    
    private void setEditableLoaiSanPham(boolean isEditableLoaiSanPham) {
            this.isEditableLoaiSanPham = isEditableLoaiSanPham;

            btn_themLoaiSanPham.setEnabled(!isEditableLoaiSanPham);
            btn_suaLoaiSanPham.setEnabled(!isEditableLoaiSanPham);
            btn_xoaLoaiSanPham.setEnabled(!isEditableLoaiSanPham);
            btn_luuLoaiSanPham.setEnabled(isEditableLoaiSanPham);
            btn_boquaLoaiSanPham.setEnabled(isEditableLoaiSanPham);

            txt_tenLoaiSanPham.setEditable(isEditableLoaiSanPham);
            txt_ghiChuLoaiSanPham.setEditable(isEditableLoaiSanPham);
    }
    
    private void setEditableHangSanXuat(boolean isEditableHangSanXuat) {
            this.isEditableHangSanXuat = isEditableHangSanXuat;

            btn_themHangSanXuat.setEnabled(!isEditableHangSanXuat);
            btn_suaHangSanXuat.setEnabled(!isEditableHangSanXuat);
            btn_xoaHangSanXuat.setEnabled(!isEditableHangSanXuat);
            btn_luuHangSanXuat.setEnabled(isEditableHangSanXuat);
            btn_boquaHangSanXuat.setEnabled(isEditableHangSanXuat);

            txt_tenHangSanXuat.setEditable(isEditableHangSanXuat);
            txt_ghiChuHangSanXuat.setEditable(isEditableHangSanXuat);
    }
    
    DefaultTableModel modeLoaiSanPham = new DefaultTableModel();
    DefaultTableModel modeHangSanXuat = new DefaultTableModel();
    
    List<LoaiSanPham> listLoaiSanPham = new ArrayList<>();
    List<HangSanXuat> listHangSanXuat = new ArrayList<>();
    
    LoaiSanPhamDAO loaiSanPhamDAO = new LoaiSanPhamDAO();
    HangSanXuatDAO hangSanXuatDAO = new HangSanXuatDAO();
    
    int indexLoaiSanPham = -1;
    int temp_indexLoaiSanPham = -1;
    int indexHangSanXuat = -1;
    int temp_indexHangSanXuat = -1;

    boolean isEditableLoaiSanPham = false;
    boolean isUpdateLoaiSanPham = false;
    boolean isEditableHangSanXuat = false;
    boolean isUpdateHangSanXuat = false;
    
    private int maLoaiSanPham;
    private String tenLoaiSanPham;
    private String ghiChuLoaiSanPham;
    private int maHangSanXuat;
    private String tenHangSanXuat;
    private String ghiChuHangSanXuat;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_boquaHangSanXuat;
    private javax.swing.JButton btn_boquaLoaiSanPham;
    private javax.swing.JButton btn_luuHangSanXuat;
    private javax.swing.JButton btn_luuLoaiSanPham;
    private javax.swing.JButton btn_suaHangSanXuat;
    private javax.swing.JButton btn_suaLoaiSanPham;
    private javax.swing.JButton btn_themHangSanXuat;
    private javax.swing.JButton btn_themLoaiSanPham;
    private javax.swing.JButton btn_xoaHangSanXuat;
    private javax.swing.JButton btn_xoaLoaiSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_HangSanXuat;
    private javax.swing.JTable tbl_LoaiSanPham;
    private javax.swing.JTextArea txt_ghiChuHangSanXuat;
    private javax.swing.JTextArea txt_ghiChuLoaiSanPham;
    private javax.swing.JTextField txt_maHangSanXuat;
    private javax.swing.JTextField txt_maLoaiSanPham;
    private javax.swing.JTextField txt_tenHangSanXuat;
    private javax.swing.JTextField txt_tenLoaiSanPham;
    // End of variables declaration//GEN-END:variables
}
