package view;

import dao.NhaPhanPhoiDAO;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.NhaPhanPhoi;

/**
 *
 * @author Hoang
 */
public class Panel_NhaPhanPhoi extends javax.swing.JPanel {

    /**
     * Creates new form panel_san_pham
     */
    public Panel_NhaPhanPhoi() {
        initComponents();
    }

    public void setdata(){
        modelNhaPhanPhoi.addColumn("Mã Nhà Phân Phối");
        modelNhaPhanPhoi.addColumn("Tên Nhà Phân Phối");
        modelNhaPhanPhoi.addColumn("Địa Chỉ");
        modelNhaPhanPhoi.addColumn("Số ĐT");
        modelNhaPhanPhoi.addColumn("Email");
        modelNhaPhanPhoi.addColumn("Ghi Chú");
        
        tbl_NhaPhanPhoi.setModel(modelNhaPhanPhoi);
        
        tbl_NhaPhanPhoi.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexNhaPhanPhoi = tbl_NhaPhanPhoi.getSelectedRow();
            if(indexNhaPhanPhoi>=0 && !isEditable){
                txt_maNhaPhanPhoi.setText(tbl_NhaPhanPhoi.getValueAt(indexNhaPhanPhoi, 0).toString());
                txt_tenNhaPhanPhoi.setText(tbl_NhaPhanPhoi.getValueAt(indexNhaPhanPhoi, 1).toString());
                txt_diaChi.setText(tbl_NhaPhanPhoi.getValueAt(indexNhaPhanPhoi, 2).toString());
                txt_soDienThoai.setText(tbl_NhaPhanPhoi.getValueAt(indexNhaPhanPhoi, 3).toString());
                txt_email.setText(tbl_NhaPhanPhoi.getValueAt(indexNhaPhanPhoi, 4).toString());
                txt_ghiChu.setText(tbl_NhaPhanPhoi.getValueAt(indexNhaPhanPhoi, 5)==null?"":tbl_NhaPhanPhoi.getValueAt(indexNhaPhanPhoi, 5).toString());
                
            } else if (isUpdate){
                
            } else if (isEditable){
                
            }
        });
        
        loadNhaPhanPhoi();
        
        setEditable(false);
        txt_maNhaPhanPhoi.setEditable(false);
        try {
            if(modelNhaPhanPhoi.getRowCount()>0) tbl_NhaPhanPhoi.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }
    
    public void loadNhaPhanPhoi(){
        setEditable(false);
        isUpdate = false;
        listNhaPhanPhoi.clear();
        modelNhaPhanPhoi.setRowCount(0);
        
        listNhaPhanPhoi = nhaPhanPhoiDAO.getList();
        listNhaPhanPhoi.forEach(nhaPhanPhoi -> {
            Vector row = new Vector();
            row.add(nhaPhanPhoi.getMaNhaPhanPhoi());
            row.add(nhaPhanPhoi.getTenNhaPhanPhoi());
            row.add(nhaPhanPhoi.getDiaChi());
            row.add(nhaPhanPhoi.getSoDienThoai());
            row.add(nhaPhanPhoi.getEmail());
            row.add(nhaPhanPhoi.getGhiChu());
            modelNhaPhanPhoi.addRow(row);
        });
        try {
            if(modelNhaPhanPhoi.getRowCount()>0) tbl_NhaPhanPhoi.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhaPhanPhoi = new javax.swing.JTable();
        txt_tenNhaPhanPhoi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_boqua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        txt_maNhaPhanPhoi = new javax.swing.JTextField();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        btn_lamMoiDanhSach = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JTextField();
        txt_diaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();

        tbl_NhaPhanPhoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhà Phân Phối", "Tên Nhà Phân Phối", "Địa Chỉ", "Số ĐT", "Email", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tbl_NhaPhanPhoi);

        jLabel1.setText("Mã Nhà Phân Phối");

        jLabel2.setText("Tên Nhà Phân Phối");

        btn_boqua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/boqua.png"))); // NOI18N
        btn_boqua.setText("Bỏ Qua");
        btn_boqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_boquaActionPerformed(evt);
            }
        });

        jLabel3.setText("Địa Chỉ");

        jLabel4.setText("Số ĐT");

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChu);

        jLabel8.setText("Ghi Chú");

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_them.setText("Tạo Mới");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/sua.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/xoa.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_timkiem.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/timkiem.png"))); // NOI18N
        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_lamMoiDanhSach.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btn_lamMoiDanhSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/refresh.png"))); // NOI18N
        btn_lamMoiDanhSach.setText("Làm Mới Danh Sách");
        btn_lamMoiDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiDanhSachActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 13)); // NOI18N
        jLabel7.setText("* Tìm kiếm đối tác theo tên hoặc số ĐT hoặc email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_timkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_lamMoiDanhSach))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lamMoiDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_tenNhaPhanPhoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(txt_maNhaPhanPhoi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_diaChi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(472, 472, 472)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_them, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(btn_luu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(btn_boqua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(btn_sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 358, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_maNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_tenNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_boqua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        temp_indexNhaPhanPhoi = indexNhaPhanPhoi;
        setEditable(true);
        txt_maNhaPhanPhoi.setText("");
        txt_tenNhaPhanPhoi.requestFocus();
        txt_tenNhaPhanPhoi.setText("");
        txt_diaChi.setText("");
        txt_soDienThoai.setText("");
        txt_email.setText("");
        txt_ghiChu.setText("");
        tbl_NhaPhanPhoi.clearSelection();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        temp_indexNhaPhanPhoi = indexNhaPhanPhoi;
        setEditable(true);
        isUpdate = true;
        txt_tenNhaPhanPhoi.requestFocus();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        temp_indexNhaPhanPhoi = indexNhaPhanPhoi;
        JLabel confirm = new JLabel("Xác nhận xóa nhà phân phối "+txt_tenNhaPhanPhoi.getText()+"?");
        confirm.setFont(new Font("Dialog", Font.PLAIN, 17));
        int a = JOptionPane.showConfirmDialog(this, confirm, "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == JOptionPane.YES_OPTION) {
            maNhaPhanPhoi = txt_maNhaPhanPhoi.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maNhaPhanPhoi.getText()) : -1;
            if (indexNhaPhanPhoi >= 0) {
                try {
                    nhaPhanPhoiDAO.xoa(maNhaPhanPhoi);
                    loadNhaPhanPhoi();
                    if(temp_indexNhaPhanPhoi == 0) tbl_NhaPhanPhoi.setRowSelectionInterval(0, 0);
                    else tbl_NhaPhanPhoi.setRowSelectionInterval(temp_indexNhaPhanPhoi-1, temp_indexNhaPhanPhoi-1);
                    
                } catch(IllegalArgumentException iea){
                } catch (Exception e4){
                    System.out.println(e4);
                }
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (checkValidate()) {
            if (!isUpdate) {
                try {
                    nhaPhanPhoiDAO.them(tenNhaPhanPhoi, diaChi, soDienThoai, email, ghiChu);
                    loadNhaPhanPhoi();
                    tbl_NhaPhanPhoi.setRowSelectionInterval(modelNhaPhanPhoi.getRowCount()-1, modelNhaPhanPhoi.getRowCount()-1);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi thêm nhà phân phối");
                    System.out.println(e);
                }
            } else {
                try {
                    nhaPhanPhoiDAO.sua(maNhaPhanPhoi, tenNhaPhanPhoi, diaChi, soDienThoai, email, ghiChu);
                    loadNhaPhanPhoi();
                    tbl_NhaPhanPhoi.clearSelection();
                    tbl_NhaPhanPhoi.setRowSelectionInterval(temp_indexNhaPhanPhoi, temp_indexNhaPhanPhoi);

                } catch (IllegalArgumentException iae){
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi sửa nhà phân phối");
                    System.out.println(e);
                } 
            }
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_boquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_boquaActionPerformed
        // TODO add your handling code here:
        setEditable(false);
        isUpdate = false;
        try {
            tbl_NhaPhanPhoi.clearSelection();
            tbl_NhaPhanPhoi.setRowSelectionInterval(temp_indexNhaPhanPhoi, temp_indexNhaPhanPhoi);
        } catch (Exception e) {}
    }//GEN-LAST:event_btn_boquaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String text = txt_timKiem.getText().trim();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập dữ liệu tìm kiếm");
            
        } else {
            listNhaPhanPhoi.clear();
            modelNhaPhanPhoi.setRowCount(0);
            listNhaPhanPhoi = nhaPhanPhoiDAO.timKiem(text);
            listNhaPhanPhoi.forEach(nhaPhanPhoi -> {
                Vector row = new Vector();
                row.add(nhaPhanPhoi.getMaNhaPhanPhoi());
                row.add(nhaPhanPhoi.getTenNhaPhanPhoi());
                row.add(nhaPhanPhoi.getDiaChi());
                row.add(nhaPhanPhoi.getSoDienThoai());
                row.add(nhaPhanPhoi.getEmail());
                row.add(nhaPhanPhoi.getGhiChu());
                modelNhaPhanPhoi.addRow(row);
            });
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_lamMoiDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiDanhSachActionPerformed
        // TODO add your handling code here:
        loadNhaPhanPhoi();
    }//GEN-LAST:event_btn_lamMoiDanhSachActionPerformed

    private boolean checkValidate() {
        maNhaPhanPhoi = txt_maNhaPhanPhoi.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maNhaPhanPhoi.getText()) : -1;
        tenNhaPhanPhoi = txt_tenNhaPhanPhoi.getText().trim();
        diaChi = txt_diaChi.getText().trim();
        soDienThoai = txt_soDienThoai.getText().trim();
        email = txt_email.getText().trim();
        ghiChu = txt_ghiChu.getText().trim();
        
        if(tenNhaPhanPhoi.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Tên Nhà phân phối");
            txt_tenNhaPhanPhoi.requestFocus();
            return false;
        }
        if(diaChi.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Địa Chỉ");
            txt_diaChi.requestFocus();
            return false;
        }
        if(soDienThoai.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Số ĐT");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(email.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Email");
            txt_email.requestFocus();
            return false;
        }
        if(tenNhaPhanPhoi.length()>50){
            JOptionPane.showMessageDialog(this, "Tên nhà phân phối phải nhỏ hơn 50 kí tự");
            txt_tenNhaPhanPhoi.requestFocus();
            return false;
        }
        if(diaChi.length()>100){
            JOptionPane.showMessageDialog(this, "Địa chỉ phải nhỏ hơn 100 kí tự");
            txt_diaChi.requestFocus();
            return false;
        }
        if(!soDienThoai.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Số ĐT không hợp lệ");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(soDienThoai.length()<8 || soDienThoai.length()>10){
            JOptionPane.showMessageDialog(this, "Nhập số điện thoại có độ dài từ 8 đến 10 kí tự");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(!email.matches("\\w+@+\\w+.+\\w")){
            JOptionPane.showMessageDialog(this, "Email không hợp lệ");
            txt_email.requestFocus();
            return false;
        }
        if(email.length()>50){
            JOptionPane.showMessageDialog(this, "Email phải nhỏ hơn 50 kí tự");
            txt_email.requestFocus();
            return false;
        }
        if(ghiChu.length()>100){
            JOptionPane.showMessageDialog(this, "Ghi chú phải nhỏ hơn 100 kí tự");
            txt_ghiChu.requestFocus();
            return false;
        }
        return true;
    }
    
    private void setEditable(boolean isEditable) {
            this.isEditable = isEditable;

            btn_them.setEnabled(!isEditable);
            btn_sua.setEnabled(!isEditable);
            btn_xoa.setEnabled(!isEditable);
            btn_luu.setEnabled(isEditable);
            btn_boqua.setEnabled(isEditable);
            btn_timkiem.setEnabled(!isEditable);

            txt_tenNhaPhanPhoi.setEditable(isEditable);
            txt_diaChi.setEditable(isEditable);
            txt_soDienThoai.setEditable(isEditable);
            txt_email.setEditable(isEditable);
            txt_ghiChu.setEditable(isEditable);

//            if (isEditable) {
//                cbo_.setModel(model_cbo_);
//                cbo_.setModel(model_cbo_);
//            }
    }
    
    DefaultTableModel modelNhaPhanPhoi = new DefaultTableModel();
    
    List<NhaPhanPhoi> listNhaPhanPhoi = new ArrayList<>();
    
    NhaPhanPhoiDAO nhaPhanPhoiDAO = new NhaPhanPhoiDAO();
    
    int indexNhaPhanPhoi = -1;
    int temp_indexNhaPhanPhoi = -1;

    boolean isEditable = false;
    boolean isUpdate = false;
    
    private int maNhaPhanPhoi;
    private String tenNhaPhanPhoi;
    private String diaChi;
    private String soDienThoai;
    private String email;
    private String ghiChu;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_boqua;
    private javax.swing.JButton btn_lamMoiDanhSach;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_NhaPhanPhoi;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextArea txt_ghiChu;
    private javax.swing.JTextField txt_maNhaPhanPhoi;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_tenNhaPhanPhoi;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
