package view;

import dao.PhieuNhapChiTietDAO;
import dao.PhieuNhapDAO;
import dao.SanPhamDAO;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.PhieuNhapChiTiet;
import model.SanPham;

/**
 *
 * @author Hoang
 */
public class Panel_PhieuNhap extends javax.swing.JPanel {

    /**
     * Creates new form panel_san_pham
     */
    public Panel_PhieuNhap() {
        initComponents();
    }

    public void setdata(){
        modelPhieuNhapChiTiet.addColumn("STT");
        modelPhieuNhapChiTiet.addColumn("Mã SP");
        modelPhieuNhapChiTiet.addColumn("Tên SP");
        modelPhieuNhapChiTiet.addColumn("Tồn Kho");
        modelPhieuNhapChiTiet.addColumn("Số Lượng Nhập");
        modelPhieuNhapChiTiet.addColumn("Giá Nhập");
        modelPhieuNhapChiTiet.addColumn("Thành Tiền");
        
        tbl_PhieuNhap.setModel(modelPhieuNhapChiTiet);
        tbl_PhieuNhap.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbl_PhieuNhap.getColumnModel().getColumn(2).setPreferredWidth(300);
        tbl_PhieuNhap.getColumnModel().getColumn(3).setPreferredWidth(50);
        tbl_PhieuNhap.getColumnModel().getColumn(4).setPreferredWidth(50);
        tbl_PhieuNhap.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbl_PhieuNhap.getColumnModel().getColumn(6).setPreferredWidth(150);
        
        tbl_PhieuNhap.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexPhieuNhapChiTiet = tbl_PhieuNhap.getSelectedRow();
        });

        txt_maSanPham.setEditable(false);
        txt_tenSanPham.setEditable(false);
        txt_tenNhaPhanPhoi.setEditable(false);
        txt_soDienThoai.setEditable(false);
        txt_loaiSanPham.setEditable(false);
        txt_hangSanXuat.setEditable(false);
        txt_diaChi.setEditable(false);
        txt_email.setEditable(false);
        txt_TongTien.setEditable(false);
        txt_TongTien.setText("0 đ");
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_PhieuNhap = new javax.swing.JTable();
        txt_tenSanPham = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_maSanPham = new javax.swing.JTextField();
        btn_xoaPhieuNhap = new javax.swing.JButton();
        btn_themPhieuNhap = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        txt_soluong = new javax.swing.JTextField();
        btn_timSanPham = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_loaiSanPham = new javax.swing.JTextField();
        txt_hangSanXuat = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_tenNhaPhanPhoi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_timNhaPhanPhoi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        txt_diaChi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_xoaTatCa = new javax.swing.JButton();
        btn_luuPhieuNhap = new javax.swing.JButton();

        tbl_PhieuNhap.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tbl_PhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Tồn Kho", "Số Lượng Nhập", "Giá Nhập", "Thành Tiền"
            }
        ));
        tbl_PhieuNhap.setRowHeight(20);
        tbl_PhieuNhap.getTableHeader().setFont(new Font("Dialog", 0, 14));
        jScrollPane1.setViewportView(tbl_PhieuNhap);

        jLabel1.setText("Mã Sản PHẩm");

        jLabel2.setText("Tên Sản Phẩm");

        jLabel3.setText("Số Lượng Nhập");

        btn_xoaPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/xoa.png"))); // NOI18N
        btn_xoaPhieuNhap.setText("Xóa Khỏi Phiếu Nhập");
        btn_xoaPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaPhieuNhapActionPerformed(evt);
            }
        });

        btn_themPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_themPhieuNhap.setText("Thêm Vào Phiếu Nhập");
        btn_themPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themPhieuNhapActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Tổng TIền");

        txt_TongTien.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txt_TongTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        txt_soluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_soluongKeyPressed(evt);
            }
        });

        btn_timSanPham.setText("Tìm SP");
        btn_timSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timSanPhamActionPerformed(evt);
            }
        });

        jLabel4.setText("Loại Sản Phẩm");

        jLabel5.setText("Hãng Sản Xuất");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setText("Tên Nhà Phân Phối");

        btn_timNhaPhanPhoi.setText("Tìm NPP");
        btn_timNhaPhanPhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timNhaPhanPhoiActionPerformed(evt);
            }
        });

        jLabel7.setText("Số ĐT");

        jLabel8.setText("Địa Chỉ");

        jLabel9.setText("Ghi Chú");

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane2.setViewportView(txt_ghiChu);

        jLabel11.setText("Email");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_tenNhaPhanPhoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_timNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_soDienThoai)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(txt_diaChi)
                            .addComponent(txt_email))
                        .addContainerGap(53, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tenNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timNhaPhanPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btn_xoaTatCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/broom2.png"))); // NOI18N
        btn_xoaTatCa.setText("Xóa Tất Cả");
        btn_xoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTatCaActionPerformed(evt);
            }
        });

        btn_luuPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luuPhieuNhap.setText("Lưu Phiếu Nhập");
        btn_luuPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuPhieuNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_maSanPham)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_timSanPham))
                            .addComponent(txt_soluong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_loaiSanPham)
                            .addComponent(txt_hangSanXuat)
                            .addComponent(txt_tenSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_themPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_xoaPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_xoaTatCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_luuPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_maSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_timSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_themPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_loaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoaTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_hangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_luuPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timSanPhamActionPerformed
        // TODO add your handling code here:
        new Popup_TimKiemSanPham(1).setVisible(true);
    }//GEN-LAST:event_btn_timSanPhamActionPerformed

    private void btn_themPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themPhieuNhapActionPerformed
        // TODO add your handling code here:
        themPhieuNhap();
    }//GEN-LAST:event_btn_themPhieuNhapActionPerformed

    private void themPhieuNhap(){
        if (checkValidatePhieuNhapChiTiet()) {
            try {
                addListPhieuNhapChiTiet();
                loadModelPhieuNhapChiTiet();
                
                txt_maSanPham.setText("");
                txt_tenSanPham.setText("");
                txt_loaiSanPham.setText("");
                txt_hangSanXuat.setText("");
                txt_soluong.setText("");
                
                tbl_PhieuNhap.setRowSelectionInterval(modelPhieuNhapChiTiet.getRowCount() - 1, modelPhieuNhapChiTiet.getRowCount() - 1);

            } catch (IllegalArgumentException iae) {
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi thêm phiếu nhập");
                System.out.println(e);
            }
        }
    }
    
    private void addListPhieuNhapChiTiet(){
        boolean isDuplicate = false;
        for (PhieuNhapChiTiet phieuNhapChiTiet : listPhieuNhapChiTiet) {
            if (phieuNhapChiTiet.getSanPham().getMaSanPham() == maSanPham) {
                isDuplicate = true;
                phieuNhapChiTiet.setSoLuong(phieuNhapChiTiet.getSoLuong()+soLuong);
                break;
            }
        }
        if (!isDuplicate) {
            PhieuNhapChiTiet phieuNhapChiTiet = new PhieuNhapChiTiet();
            phieuNhapChiTiet.setSanPham(sanPham);
            phieuNhapChiTiet.setSoLuong(soLuong);
            listPhieuNhapChiTiet.add(phieuNhapChiTiet);
        }
    }
    
    private void btn_xoaPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaPhieuNhapActionPerformed
        // TODO add your handling code here:
        temp_indexPhieuNhapChiTiet = indexPhieuNhapChiTiet;

        maSanPham = txt_maSanPham.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maSanPham.getText()) : -1;
        if (indexPhieuNhapChiTiet >= 0) {
            try {
                listPhieuNhapChiTiet.remove(indexPhieuNhapChiTiet);
                loadModelPhieuNhapChiTiet();
                
                if (temp_indexPhieuNhapChiTiet == 0) {
                    tbl_PhieuNhap.setRowSelectionInterval(0, 0);
                } else {
                    tbl_PhieuNhap.setRowSelectionInterval(temp_indexPhieuNhapChiTiet - 1, temp_indexPhieuNhapChiTiet - 1);
                }

            } catch (IllegalArgumentException iea) {
            } catch (Exception e4) {
                System.out.println(e4);
            }
        }
    }//GEN-LAST:event_btn_xoaPhieuNhapActionPerformed

    private void btn_timNhaPhanPhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timNhaPhanPhoiActionPerformed
        // TODO add your handling code here:
        new Popup_TimKiemNhaPhanPhoi().setVisible(true);
    }//GEN-LAST:event_btn_timNhaPhanPhoiActionPerformed

    private void txt_soluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soluongKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            themPhieuNhap();
        }
    }//GEN-LAST:event_txt_soluongKeyPressed

    private void btn_xoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTatCaActionPerformed
        // TODO add your handling code here:
        xoaTatCa();
    }//GEN-LAST:event_btn_xoaTatCaActionPerformed

    public void xoaTatCa(){
        try {
            listPhieuNhapChiTiet.clear();
            loadModelPhieuNhapChiTiet();
            
            maNhaPhanPhoi = -1;
            txt_tenNhaPhanPhoi.setText("");
            txt_soDienThoai.setText("");
            txt_ghiChu.setText("");
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void btn_luuPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuPhieuNhapActionPerformed
        // TODO add your handling code here:
        if (checkValidatePhieuNhap()) {
            phieuNhapDAO.them(taiKhoan, maNhaPhanPhoi, tongTien, ngayNhap, ghiChu, listPhieuNhapChiTiet);
            JOptionPane.showMessageDialog(this, "Lưu phiếu nhập thành công");
            xoaTatCa();
        }
    }//GEN-LAST:event_btn_luuPhieuNhapActionPerformed

    private boolean checkValidatePhieuNhapChiTiet() {
        maSanPham = txt_maSanPham.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_maSanPham.getText()) : -1;
        soLuong = txt_soluong.getText().trim().matches("[0-9]+") ? Integer.valueOf(txt_soluong.getText()) : -1;
        
        if(maSanPham==-1){
            JOptionPane.showMessageDialog(this, "Chưa chọn SP");
            return false;
        }
        if(soLuong<1){
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ");
            txt_soluong.requestFocus();
            return false;
        }
        
        sanPham = sanPhamDAO.getSanPhamById(maSanPham);
        
        
        return true;
    }
    
    private boolean checkValidatePhieuNhap() {
        taiKhoan = TrangChu.taiKhoan;
        if(maNhaPhanPhoi==-1 || txt_tenNhaPhanPhoi.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa chọn Khách Hàng");
            return false;
        }
        if(listPhieuNhapChiTiet.isEmpty() || modelPhieuNhapChiTiet.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Chưa chọn SP");
            return false;
        }
        
        ngayNhap = format.format(new java.util.Date());
        ghiChu = txt_ghiChu.getText();
        return true;
    }
    
    private void loadModelPhieuNhapChiTiet(){
        int stt = 1;
        tongTien = 0;
        modelPhieuNhapChiTiet.setRowCount(0);
        for (PhieuNhapChiTiet phieuNhapChiTiet : listPhieuNhapChiTiet) {
            Vector row = new Vector();
            row.add(stt++);
            row.add(phieuNhapChiTiet.getSanPham().getMaSanPham());
            row.add(phieuNhapChiTiet.getSanPham().getTenSanPham());
            row.add(phieuNhapChiTiet.getSanPham().getTonKho());
            row.add(phieuNhapChiTiet.getSoLuong());
            row.add(formatGia(phieuNhapChiTiet.getSanPham().getGiaNhap()));
            int thanhTien = phieuNhapChiTiet.getSanPham().getGiaNhap()*phieuNhapChiTiet.getSoLuong();
            row.add(formatGia(thanhTien));
            modelPhieuNhapChiTiet.addRow(row);
            tongTien += thanhTien;
        }
        txt_TongTien.setText(formatGia(tongTien));
    }
    
    SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    DefaultTableModel modelPhieuNhapChiTiet = new DefaultTableModel();
    
    List<PhieuNhapChiTiet> listPhieuNhapChiTiet = new ArrayList<>();
    
    PhieuNhapDAO phieuNhapDAO = new PhieuNhapDAO();
    PhieuNhapChiTietDAO phieuNhapChiTietDAO = new PhieuNhapChiTietDAO();
    SanPhamDAO sanPhamDAO = new SanPhamDAO();
    
    int indexPhieuNhapChiTiet = -1;
    int temp_indexPhieuNhapChiTiet = -1;

    private String taiKhoan;
    private int maSanPham;
    private int soLuong;
    private long tongTien = 0;
    static int maNhaPhanPhoi = -1;
    private SanPham sanPham;
    private String ngayNhap;
    private String ghiChu;
    
    public static String formatGia(int gia){
        return new DecimalFormat("#,###").format(gia).replace(",", ".") + " đ";
    }
    public static String formatGia(long gia){
        return new DecimalFormat("#,###").format(gia).replace(",", ".") + " đ";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luuPhieuNhap;
    private javax.swing.JButton btn_themPhieuNhap;
    private javax.swing.JButton btn_timNhaPhanPhoi;
    private javax.swing.JButton btn_timSanPham;
    private javax.swing.JButton btn_xoaPhieuNhap;
    private javax.swing.JButton btn_xoaTatCa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_PhieuNhap;
    private javax.swing.JTextField txt_TongTien;
    protected static javax.swing.JTextField txt_diaChi;
    protected static javax.swing.JTextField txt_email;
    protected static javax.swing.JTextArea txt_ghiChu;
    protected static javax.swing.JTextField txt_hangSanXuat;
    protected static javax.swing.JTextField txt_loaiSanPham;
    protected static javax.swing.JTextField txt_maSanPham;
    protected static javax.swing.JTextField txt_soDienThoai;
    protected static javax.swing.JTextField txt_soluong;
    protected static javax.swing.JTextField txt_tenNhaPhanPhoi;
    protected static javax.swing.JTextField txt_tenSanPham;
    // End of variables declaration//GEN-END:variables
}
