
package view;

import dao.NhanVienDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoang
 */
public class Popup_DoiMatKhau extends javax.swing.JFrame {

    /** Creates new form Popup_DoiMatKhau
     @param isNewNhanVien
     */
    public Popup_DoiMatKhau(boolean isNewNhanVien) {
        initComponents();
        setLocationRelativeTo(null);
        this.isNewNhanVien = isNewNhanVien;
        setdata();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pw_old = new javax.swing.JPasswordField();
        pw_new = new javax.swing.JPasswordField();
        pw_new2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btn_XacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đổi Mật Khẩu");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel1.setText("Nhập Mật Khẩu Cũ");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel2.setText("Nhập Mật Khẩu Mới");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel3.setText("Nhập Lại Mật Khẩu Mới");

        pw_old.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        pw_new.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        pw_new2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("ĐỔI MẬT KHẨU");

        btn_XacNhan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_XacNhan.setText("Xác Nhận");
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_XacNhan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pw_new, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pw_old, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pw_new2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pw_old, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pw_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pw_new2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_XacNhan)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        // TODO add your handling code here:
        if(checkValidate()){
            nhanVienDAO.doiMatKhau(taiKhoan, password_new);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
            if(isNewNhanVien){
                new TrangChu().setVisible(true);
            }
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_btn_XacNhanActionPerformed

    private boolean checkValidate(){
        taiKhoan = TrangChu.taiKhoan;
        password_old = new String(pw_old.getPassword());
        password_new = new String(pw_new.getPassword());
        password_new2 = new String(pw_new2.getPassword());
        
        if(password_old.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập mật khẩu cũ");
            pw_old.requestFocus();
            return false;
        }
        if(password_new.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập mật khẩu mới");
            pw_new.requestFocus();
            return false;
        }
        if(password_new.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập lại mật khẩu mới");
            pw_new2.requestFocus();
            return false;
        }
        if(!nhanVienDAO.checkDangNhap(taiKhoan, password_old)){
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ không đúng");
            return false;
        }        
        if(!password_new.matches("[A-Za-z0-9 ]+")){
            JOptionPane.showMessageDialog(this, "Mật khẩu chỉ được chứa kí tự chữ và số");
            pw_new.requestFocus();
            return false;
        }
        if(password_new.length()<8){
            JOptionPane.showMessageDialog(this, "Mật khẩu phải có độ dài từ 8 kí tự trở lên");
            pw_new.requestFocus();
            return false;
        }
        if(password_new.length()>30){
            JOptionPane.showMessageDialog(this, "Mật khẩu phải nhỏ hơn 30 kí tự");
            pw_new.requestFocus();
            return false;
        }
        if(!password_new2.equals(password_new)){
            JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không khớp");
            pw_new2.requestFocus();
            return false;
        }
        
        return true;
    }
    
    public void setdata(){
        if(isNewNhanVien){
            setTitle("Đăng Nhập Lần Đầu");
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popup_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popup_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popup_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popup_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popup_DoiMatKhau(false).setVisible(true);
            }
        });
    }

    NhanVienDAO nhanVienDAO = new NhanVienDAO();

    String taiKhoan;
    String password_old;
    String password_new;
    String password_new2;
    boolean isNewNhanVien;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pw_new;
    private javax.swing.JPasswordField pw_new2;
    private javax.swing.JPasswordField pw_old;
    // End of variables declaration//GEN-END:variables

}
