
package view;

import dao.KhachHangDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;

public class Popup_TimKiemKhachHang extends javax.swing.JFrame {

    /** Creates new form TimKiemSanPham */
    public Popup_TimKiemKhachHang() {
        initComponents();
        setLocationRelativeTo(null);
        setdata();
    }

    public void setdata(){
        setResizable(false);
        modelKhachHang.addColumn("Tên Khách Hàng");
        modelKhachHang.addColumn("Giới Tính");
        modelKhachHang.addColumn("Số ĐT");
        modelKhachHang.addColumn("Ghi Chú");
        
        tbl_KhachHang.setModel(modelKhachHang);
        tbl_KhachHang.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            indexKhachHang = tbl_KhachHang.getSelectedRow();
        });
        txt_timKiem.requestFocus();
        listKhachHang = khachHangDAO.getList();
        loadModelKhachHang();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KhachHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_timKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();
        btn_chonKH = new javax.swing.JButton();
        btn_themKH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tìm Kiếm theo Tên KH hoặc số ĐT");

        tbl_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Khách Hàng", "Giới Tính", "Số ĐT", "Ghi Chú"
            }
        ));
        tbl_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhachHangMouseClicked(evt);
            }
        });
        tbl_KhachHang.setDefaultEditor(Object.class, null);
        jScrollPane1.setViewportView(tbl_KhachHang);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Nhập:");

        txt_timKiem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_timKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_timKiemKeyPressed(evt);
            }
        });

        btn_TimKiem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/timkiem.png"))); // NOI18N
        btn_TimKiem.setText("Tìm Kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_chonKH.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_chonKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/checked.png"))); // NOI18N
        btn_chonKH.setText("Chọn KH");
        btn_chonKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonKHActionPerformed(evt);
            }
        });

        btn_themKH.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        btn_themKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/them.png"))); // NOI18N
        btn_themKH.setText("Thêm Khách Hàng Mới");
        btn_themKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_TimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(btn_chonKH))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_themKH)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem)
                    .addComponent(btn_chonKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_themKH)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timKiemKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            timKiem();
        }
    }//GEN-LAST:event_txt_timKiemKeyPressed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_chonKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonKHActionPerformed
        // TODO add your handling code here:
        if(indexKhachHang>=0){
            chonKH();
            
        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn SP");
        }
    }//GEN-LAST:event_btn_chonKHActionPerformed

    private void tbl_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhachHangMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            chonKH();
        }
    }//GEN-LAST:event_tbl_KhachHangMouseClicked

    private void btn_themKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themKHActionPerformed
        // TODO add your handling code here:
        new PopUp_ThemKhachHang(this).setVisible(true);
    }//GEN-LAST:event_btn_themKHActionPerformed

    private void chonKH() {
        Panel_DonHang.txt_tenKhachHang.setText(tbl_KhachHang.getValueAt(indexKhachHang, 0).toString());
        if(tbl_KhachHang.getValueAt(indexKhachHang, 1).toString().equals("Nam")) {
            Panel_DonHang.rdo_nam.setSelected(true);
        } else {
            Panel_DonHang.rdo_nu.setSelected(true);
        }
        Panel_DonHang.txt_soDienThoai.setText(tbl_KhachHang.getValueAt(indexKhachHang, 2).toString());
        Panel_DonHang.maKhachHang = listKhachHang.get(indexKhachHang).getMaKhachHang();
        setVisible(false);
        dispose();
    }
    
    private void timKiem(){
        String text = txt_timKiem.getText().trim();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập thông tin Khách Hàng");
            
        } else {
            listKhachHang = khachHangDAO.timKiem(text);
            loadModelKhachHang();
        }
    }
    
    private void loadModelKhachHang() {
        modelKhachHang.setRowCount(0);
        listKhachHang.forEach(khachHang -> {
            Vector row = new Vector();
            row.add(khachHang.getTenKhachHang());
            row.add(khachHang.isGioiTinh() == true ? "Nam" : "Nữ");
            row.add(khachHang.getSoDienThoai());
            row.add(khachHang.getGhiChu());
            modelKhachHang.addRow(row);
        });

        try {
            if (modelKhachHang.getRowCount() > 0) {
                tbl_KhachHang.setRowSelectionInterval(0, 0);
            }
        } catch (Exception e) {}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popup_TimKiemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popup_TimKiemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popup_TimKiemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popup_TimKiemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popup_TimKiemKhachHang().setVisible(true);
            }
        });
    }

    DefaultTableModel modelKhachHang = new DefaultTableModel();
    
    List<KhachHang> listKhachHang = new ArrayList<>();
    
    KhachHangDAO khachHangDAO = new KhachHangDAO();
    
    int indexKhachHang = -1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_chonKH;
    private javax.swing.JButton btn_themKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_KhachHang;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables

}
