
package view;

import dao.KhachHangDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoang
 */
public class PopUp_ThemKhachHang extends javax.swing.JFrame {

    /** Creates new form PopUp_ThemKhachHang
     * @param popup_timkiem
     */
    public PopUp_ThemKhachHang(JFrame popup_timkiem) {
        initComponents();
        setLocationRelativeTo(null);
        txt_tenKhachHang.requestFocus();
        this.popup_timkiem = popup_timkiem;
        rdo_nam.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_gioiTinh = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txt_tenKhachHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ghiChu = new javax.swing.JTextArea();
        btn_luu = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm Khách Hàng Mới");

        jLabel2.setText("Họ Tên");

        jLabel3.setText("Giới Tính");

        grp_gioiTinh.add(rdo_nam);
        rdo_nam.setText("Nam");

        grp_gioiTinh.add(rdo_nu);
        rdo_nu.setText("Nữ");

        jLabel4.setText("Số ĐT");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Thêm Khách Hàng Mới");

        jLabel8.setText("Ghi Chú");

        txt_ghiChu.setColumns(20);
        txt_ghiChu.setRows(5);
        jScrollPane1.setViewportView(txt_ghiChu);

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/luu.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/boqua.png"))); // NOI18N
        btn_lammoi.setText("Làm Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdo_nam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_nu))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_soDienThoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_lammoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_luu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdo_nam)
                    .addComponent(rdo_nu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_luu)
                    .addComponent(btn_lammoi))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        txt_tenKhachHang.setText("");
        txt_tenKhachHang.requestFocus();
        rdo_nam.setSelected(true);
        txt_soDienThoai.setText("");
        txt_ghiChu.setText("");
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if (checkValidate()) {
            try {
                khachHangDAO.them(tenKhachHang, gioiTinh, soDienThoai, ghiChu);
                Panel_DonHang.txt_tenKhachHang.setText(tenKhachHang);
                Panel_DonHang.txt_soDienThoai.setText(soDienThoai);
                if (gioiTinh) Panel_DonHang.rdo_nam.setSelected(true);
                else Panel_DonHang.rdo_nu.setSelected(true);
                Panel_DonHang.maKhachHang = khachHangDAO.getLastMaKhachHang();
                setVisible(false);
                dispose();
                this.popup_timkiem.setVisible(false);
                this.popup_timkiem.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi thêm khách hàng");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private boolean checkValidate(){
        tenKhachHang = txt_tenKhachHang.getText().trim();
        gioiTinh = rdo_nam.isSelected();
        soDienThoai = txt_soDienThoai.getText().trim();
        ghiChu = txt_ghiChu.getText().trim();
        
        if(tenKhachHang.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Tên khách hàng");
            txt_tenKhachHang.requestFocus();
            return false;
        }
        if(soDienThoai.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa nhập Số ĐT");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(tenKhachHang.length()>50){
            JOptionPane.showMessageDialog(this, "Tên khách hàng phải nhỏ hơn 50 kí tự");
            txt_tenKhachHang.requestFocus();
            return false;
        }
        if(!soDienThoai.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Số ĐT không hợp lệ");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(soDienThoai.length()<8 || soDienThoai.length()>10){
            JOptionPane.showMessageDialog(this, "Nhập số điện thoại có độ dài từ 8 đến 10 kí tự");
            txt_soDienThoai.requestFocus();
            return false;
        }
        if(ghiChu.length()>100){
            JOptionPane.showMessageDialog(this, "Ghi chú phải nhỏ hơn 100 kí tự");
            txt_ghiChu.requestFocus();
            return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp_ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp_ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp_ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp_ThemKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUp_ThemKhachHang(null).setVisible(true);
            }
        });
    }
    
    JFrame popup_timkiem;
    
    KhachHangDAO khachHangDAO = new KhachHangDAO();

    private String tenKhachHang;
    private boolean gioiTinh;
    private String soDienThoai;
    private String ghiChu;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_luu;
    private javax.swing.ButtonGroup grp_gioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTextArea txt_ghiChu;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_tenKhachHang;
    // End of variables declaration//GEN-END:variables

}
